Text_SwordsDanceTeach::
    .string "Not many people come out here.\p"
    .string "If I train here, I'm convinced that\n"
    .string "I'll get stronger and stronger.\p"
    .string "Yep, stronger and stronger…\p"
    .string "How would you like to learn a move\n"
    .string "like that? It's SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "Well, that's fine, too.$"

Text_SwordsDanceWhichMon::
    .string "All right, pick which POKéMON\n"
    .string "I should teach it to.$"

Text_SwordsDanceTaught::
    .string "If only we could keep getting\n"
    .string "stronger and stronger, eh?$"

Text_SwordsDanceReteach::
    .string "I'm still trying to get stronger\n"
    .string "and stronger…\p"
    .string "I've heard that vitamins strengthen\n"
    .string "POKéMON, but they're so expensive!\p"
    .string "So, I started charging ¥75000 to\n"
    .string "teach other POKéMON SWORDS DANCE.$"
Text_SwordsDanceReteach2::
    .string "Would you like me to teach your\n"
    .string "POKéMON the move SWORDS DANCE?$"
Text_SwordsDanceNotEnoughMoney::
    .string "You don't have ¥75000?\p"
    .string "I'm sorry, but I need the money\n"
    .string "to make my POKéMON strong.\p"
    .string "I'll teach SWORDS DANCE to you\n"
    .string "when you come back with enough.$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Quest Island of Infinity$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "These islands are called the SEVII\n"
    .string "ISLANDS because there are seven.\p"
    .string "…Or at least that's what the young\n"
    .string "people believe.\p"
    .string "The truth is, these islands are so\n"
    .string "named because they are said to\l"
    .string "have been made in seven days.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "This island has been left virtually\n"
    .string "untouched in its natural state.\p"
    .string "It could be a little difficult to\n"
    .string "hike around because of that.$"

