FourIsland_IcefallCave_B1F_Text_KSI::  
    .string "Ow… Woah, what\n"  
    .string "are you doing here?!\p"  
    .string "I'll have you know I'm\n"  
    .string "the CHAMP of FOUR ISLAND!\p"  
    .string "From the cave to the grass,\n"  
    .string "to the gym, to the league,\l"  
    .string "I'll beat you anywhere!$"  

FourIsland_IcefallCave_B1F_Text_KSIDefeat::  
    .string "…$"  

FourIsland_IcefallCave_B1F_Text_KSIPostBattle::  
    .string "Welp! Guess I lost.\p"  
    .string "That was still a good\n"  
    .string "performance, right?$"  

FourIsland_IcefallCave_B1F_Text_NoKSI::  
    .string "Not ready for my might…$"  

FourIsland_IcefallCave_B1F_Text_YesKSI::  
    .string "You're about to faint!\p"  
    .string "Let's battle!$"  

FourIsland_IcefallCave_B1F_Text_RematchKSI::  
    .string "Huh, you just want to\n"  
    .string "lose again? Be my guest!$"  

FourIsland_IcefallCave_B1F_Text_RematchKSIDefeat::  
    .string "…$"  

FourIsland_IcefallCave_B1F_Text_YesRematchKSI::  
    .string "You're about to faint!\p"  
    .string "Let's battle!$"  

FourIsland_IcefallCave_B1F_Text_RematchKSIPostBattle::  
    .string "Welp! Guess I lost.\p"  
    .string "That was still a good\n"  
    .string "performance, right?\p"  
    .string "Right?$"  
