# 1 "data/maps/RockTunnel_B1F/scripts.pory"

# 2 "data/maps/RockTunnel_B1F/scripts.pory"
.set LOCALID_MIRAGE, 27
# 3 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_MapScripts::
# 4 "data/maps/RockTunnel_B1F/scripts.pory"
	.byte 0
# 5 "data/maps/RockTunnel_B1F/scripts.pory"

# 6 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Sofia::
# 7 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat
# 8 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle, MSGBOX_AUTOCLOSE
# 9 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 10 "data/maps/RockTunnel_B1F/scripts.pory"

# 11 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Martha::
# 12 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat
# 13 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
# 14 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 15 "data/maps/RockTunnel_B1F/scripts.pory"

# 16 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Dudley::
# 17 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat
# 18 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle, MSGBOX_AUTOCLOSE
# 19 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 20 "data/maps/RockTunnel_B1F/scripts.pory"

# 21 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Allen::
# 22 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat
# 23 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
# 24 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 25 "data/maps/RockTunnel_B1F/scripts.pory"

# 26 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Eric::
# 27 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat
# 28 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle, MSGBOX_AUTOCLOSE
# 29 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 30 "data/maps/RockTunnel_B1F/scripts.pory"

# 31 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Cooper::
# 32 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat
# 33 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle, MSGBOX_AUTOCLOSE
# 34 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 35 "data/maps/RockTunnel_B1F/scripts.pory"

# 36 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Steve::
# 37 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat
# 38 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle, MSGBOX_AUTOCLOSE
# 39 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 40 "data/maps/RockTunnel_B1F/scripts.pory"

# 41 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Winston::
# 42 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat
# 43 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle, MSGBOX_AUTOCLOSE
# 44 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 45 "data/maps/RockTunnel_B1F/scripts.pory"

# 46 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_OrbingCheck::
# 47 "data/maps/RockTunnel_B1F/scripts.pory"
	lock
# 48 "data/maps/RockTunnel_B1F/scripts.pory"
	faceplayer
# 49 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_set FLAG_CAUGHT_REGIROCK, RockTunnel_B1F_EventScript_End
# 50 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_set FLAG_REGIROCK_CHECKED, RockTunnel_B1F_EventScript_Orbing
# 51 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_RegiceCheck
# 52 "data/maps/RockTunnel_B1F/scripts.pory"
	closemessage
# 53 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar VAR_0x8005, 1
# 54 "data/maps/RockTunnel_B1F/scripts.pory"
	special IsRelicanthInParty
# 55 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, 0, RockTunnel_B1F_EventScript_NoEligiblePkmn
# 56 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar 0x8004, FAMECHECKER_BRUNO
# 57 "data/maps/RockTunnel_B1F/scripts.pory"
	callnative CheckFilledFameCheckerFor0x8004
# 58 "data/maps/RockTunnel_B1F/scripts.pory"
	compare VAR_RESULT, TRUE
# 59 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq RockTunnel_B1F_EventScript_Flag
# 60 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 61 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 62 "data/maps/RockTunnel_B1F/scripts.pory"

# 63 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_NoEligiblePkmn::
# 64 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_NoEligiblePkmn
# 65 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 66 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 67 "data/maps/RockTunnel_B1F/scripts.pory"

# 68 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Flag::
# 69 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_REGIROCK_CHECKED
# 70 "data/maps/RockTunnel_B1F/scripts.pory"
	goto RockTunnel_B1F_EventScript_Orbing
# 71 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 72 "data/maps/RockTunnel_B1F/scripts.pory"

# 73 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Orbing::
# 74 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_Whitney, MSGBOX_YESNO
# 75 "data/maps/RockTunnel_B1F/scripts.pory"
	closemessage
# 76 "data/maps/RockTunnel_B1F/scripts.pory"
	delay 40
# 77 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, NO, RockTunnel_B1F_EventScript_NoWhitney
# 78 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_RS_TUBER_M, RockTunnel_B1F_Text_YesWhitney, RockTunnel_B1F_Text_PostWhitney, RockTunnel_B1F_EventScript_PostWhitney, NO_MUSIC
# 79 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 80 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 81 "data/maps/RockTunnel_B1F/scripts.pory"

# 82 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_PostWhitney::
# 83 "data/maps/RockTunnel_B1F/scripts.pory"
	special HealPlayerParty
# 84 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_WhitneyPostBattle
# 85 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_questlog EventScript_ReleaseEnd
# 86 "data/maps/RockTunnel_B1F/scripts.pory"
	special QuestLog_CutRecording
# 87 "data/maps/RockTunnel_B1F/scripts.pory"
	lock
# 88 "data/maps/RockTunnel_B1F/scripts.pory"
	faceplayer
# 89 "data/maps/RockTunnel_B1F/scripts.pory"
	setwildbattle SPECIES_REGIROCK, 70
# 90 "data/maps/RockTunnel_B1F/scripts.pory"
	waitse
# 91 "data/maps/RockTunnel_B1F/scripts.pory"
	playmoncry SPECIES_REGIROCK, CRY_MODE_ENCOUNTER
# 92 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 93 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmoncry
# 94 "data/maps/RockTunnel_B1F/scripts.pory"
	delay 10
# 95 "data/maps/RockTunnel_B1F/scripts.pory"
	playbgm MUS_ENCOUNTER_GYM_LEADER, 0
# 96 "data/maps/RockTunnel_B1F/scripts.pory"
	waitbuttonpress
# 97 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_SYS_SPECIAL_WILD_BATTLE
# 98 "data/maps/RockTunnel_B1F/scripts.pory"
	special StartLegendaryBattle
# 99 "data/maps/RockTunnel_B1F/scripts.pory"
	waitstate
# 100 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_SYS_SPECIAL_WILD_BATTLE
# 101 "data/maps/RockTunnel_B1F/scripts.pory"
	specialvar VAR_RESULT, GetBattleOutcome
# 102 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_WON, RockTunnel_B1F_EventScript_DefeatedCelebi
# 103 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, RockTunnel_B1F_EventScript_RanFromCelebi
# 104 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED, RockTunnel_B1F_EventScript_RanFromCelebi
# 105 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_CAUGHT_REGIROCK
# 106 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 107 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndWhitney
# 108 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 109 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 110 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 111 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 112 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 113 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 114 "data/maps/RockTunnel_B1F/scripts.pory"

# 115 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_DefeatedCelebi::
# 116 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_CAUGHT_REGIROCK
# 117 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 118 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndWhitney
# 119 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 120 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 121 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 122 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 123 "data/maps/RockTunnel_B1F/scripts.pory"
	goto EventScript_RemoveStaticMon
# 124 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 125 "data/maps/RockTunnel_B1F/scripts.pory"

# 126 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_RanFromCelebi::
# 127 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar VAR_0x8004, SPECIES_REGIROCK
# 128 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 129 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndWhitney
# 130 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 131 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 132 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 133 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 134 "data/maps/RockTunnel_B1F/scripts.pory"
	goto EventScript_MonFlewAway
# 135 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 136 "data/maps/RockTunnel_B1F/scripts.pory"

# 137 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_NoWhitney::
# 138 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_NoWhitney
# 139 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 140 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 141 "data/maps/RockTunnel_B1F/scripts.pory"

# 142 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_End::
# 143 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 144 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndWhitney
# 145 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 146 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 147 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 148 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK	
# 149 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 150 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 151 "data/maps/RockTunnel_B1F/scripts.pory"

# 152 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_NoEligiblePkmn::
# 153 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "You have not meet the requirements.\p"
# 154 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Come back when you do.$"
# 155 "data/maps/RockTunnel_B1F/scripts.pory"

# 156 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_RegiceCheck::
# 157 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Hello there {PLAYER}.\p"
# 158 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I am the Rocky Mirage Trainer.\p"
# 159 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Beat me and you shall face a\n"
# 160 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "special POKEMON.\p"
# 161 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "But first, I want to see a\n"
# 162 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "ANCIENT FISH,\l"
# 163 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "and knowledge on a STRONG MAN.$"
# 164 "data/maps/RockTunnel_B1F/scripts.pory"

# 165 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_Whitney::
# 166 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "So, you wish to face me?$"
# 167 "data/maps/RockTunnel_B1F/scripts.pory"

# 168 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_YesWhitney::
# 169 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Very well! Prepare yourself!$"
# 170 "data/maps/RockTunnel_B1F/scripts.pory"

# 171 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_PostWhitney::
# 172 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "So you are worthy...$"
# 173 "data/maps/RockTunnel_B1F/scripts.pory"

# 174 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_WhitneyPostBattle::
# 175 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Alright, you have bested me.\p"
# 176 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Be prepared to face REGIROCK!$"
# 177 "data/maps/RockTunnel_B1F/scripts.pory"

# 178 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_EndWhitney::
# 179 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Goodbye.$"
# 180 "data/maps/RockTunnel_B1F/scripts.pory"

# 181 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_NoWhitney::
# 182 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Alright, take your time.$"
