# 1 "data/maps/RockTunnel_B1F/scripts.pory"

# 2 "data/maps/RockTunnel_B1F/scripts.pory"
.set LOCALID_MIRAGE, 27
# 3 "data/maps/RockTunnel_B1F/scripts.pory"
.set LOCALID_REGIROCK, 28
# 4 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_MapScripts::
# 5 "data/maps/RockTunnel_B1F/scripts.pory"
	.byte 0
# 6 "data/maps/RockTunnel_B1F/scripts.pory"

# 7 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Sofia::
# 8 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat
# 9 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle, MSGBOX_AUTOCLOSE
# 10 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 11 "data/maps/RockTunnel_B1F/scripts.pory"

# 12 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Martha::
# 13 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat
# 14 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
# 15 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 16 "data/maps/RockTunnel_B1F/scripts.pory"

# 17 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Dudley::
# 18 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat
# 19 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle, MSGBOX_AUTOCLOSE
# 20 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 21 "data/maps/RockTunnel_B1F/scripts.pory"

# 22 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Allen::
# 23 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat
# 24 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
# 25 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 26 "data/maps/RockTunnel_B1F/scripts.pory"

# 27 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Eric::
# 28 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat
# 29 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle, MSGBOX_AUTOCLOSE
# 30 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 31 "data/maps/RockTunnel_B1F/scripts.pory"

# 32 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Cooper::
# 33 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat
# 34 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle, MSGBOX_AUTOCLOSE
# 35 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 36 "data/maps/RockTunnel_B1F/scripts.pory"

# 37 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Steve::
# 38 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat
# 39 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle, MSGBOX_AUTOCLOSE
# 40 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 41 "data/maps/RockTunnel_B1F/scripts.pory"

# 42 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Winston::
# 43 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat
# 44 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle, MSGBOX_AUTOCLOSE
# 45 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 46 "data/maps/RockTunnel_B1F/scripts.pory"

# 47 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_OrbingCheck::
# 48 "data/maps/RockTunnel_B1F/scripts.pory"
	lock
# 49 "data/maps/RockTunnel_B1F/scripts.pory"
	faceplayer
# 50 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_set FLAG_CAUGHT_REGIROCK, RockTunnel_B1F_EventScript_End
# 51 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_set FLAG_REGIROCK_CHECKED, RockTunnel_B1F_EventScript_Orbing
# 52 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_RegiceCheck
# 53 "data/maps/RockTunnel_B1F/scripts.pory"
	closemessage
# 54 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar VAR_0x8005, 1
# 55 "data/maps/RockTunnel_B1F/scripts.pory"
	special IsRelicanthInParty
# 56 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, 0, RockTunnel_B1F_EventScript_NoEligiblePkmn
# 57 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar 0x8004, FAMECHECKER_BRUNO
# 58 "data/maps/RockTunnel_B1F/scripts.pory"
	callnative CheckFilledFameCheckerFor0x8004
# 59 "data/maps/RockTunnel_B1F/scripts.pory"
	compare VAR_RESULT, TRUE
# 60 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq RockTunnel_B1F_EventScript_Flag
# 61 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 62 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 63 "data/maps/RockTunnel_B1F/scripts.pory"

# 64 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_NoEligiblePkmn::
# 65 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_NoEligiblePkmn
# 66 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 67 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 68 "data/maps/RockTunnel_B1F/scripts.pory"

# 69 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Flag::
# 70 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_REGIROCK_CHECKED
# 71 "data/maps/RockTunnel_B1F/scripts.pory"
	goto RockTunnel_B1F_EventScript_Orbing
# 72 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 73 "data/maps/RockTunnel_B1F/scripts.pory"

# 74 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Orbing::
# 75 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_Rock, MSGBOX_YESNO
# 76 "data/maps/RockTunnel_B1F/scripts.pory"
	closemessage
# 77 "data/maps/RockTunnel_B1F/scripts.pory"
	delay 40
# 78 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, NO, RockTunnel_B1F_EventScript_NoRock
# 79 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_single TRAINER_ROCKY, RockTunnel_B1F_Text_YesRock, RockTunnel_B1F_Text_PostRock, RockTunnel_B1F_EventScript_PostRock, NO_MUSIC
# 80 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 81 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 82 "data/maps/RockTunnel_B1F/scripts.pory"

# 83 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_PostRock::
# 84 "data/maps/RockTunnel_B1F/scripts.pory"
	special HealPlayerParty
# 85 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_RockPostBattle
# 86 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_questlog EventScript_ReleaseEnd
# 87 "data/maps/RockTunnel_B1F/scripts.pory"
	special QuestLog_CutRecording
# 88 "data/maps/RockTunnel_B1F/scripts.pory"
	lock
# 89 "data/maps/RockTunnel_B1F/scripts.pory"
	faceplayer
# 90 "data/maps/RockTunnel_B1F/scripts.pory"
	setwildbattle SPECIES_REGIROCK, 70
# 91 "data/maps/RockTunnel_B1F/scripts.pory"
	waitse
# 92 "data/maps/RockTunnel_B1F/scripts.pory"
	playmoncry SPECIES_REGIROCK, CRY_MODE_ENCOUNTER
# 93 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 94 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmoncry
# 95 "data/maps/RockTunnel_B1F/scripts.pory"
	delay 10
# 96 "data/maps/RockTunnel_B1F/scripts.pory"
	playbgm MUS_ENCOUNTER_GYM_LEADER, 0
# 97 "data/maps/RockTunnel_B1F/scripts.pory"
	waitbuttonpress
# 98 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_SYS_SPECIAL_WILD_BATTLE
# 99 "data/maps/RockTunnel_B1F/scripts.pory"
	special StartLegendaryBattle
# 100 "data/maps/RockTunnel_B1F/scripts.pory"
	waitstate
# 101 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_SYS_SPECIAL_WILD_BATTLE
# 102 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_REGIROCK
# 103 "data/maps/RockTunnel_B1F/scripts.pory"
	specialvar VAR_RESULT, GetBattleOutcome
# 104 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_WON, RockTunnel_B1F_EventScript_DefeatedCelebi
# 105 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, RockTunnel_B1F_EventScript_RanFromCelebi
# 106 "data/maps/RockTunnel_B1F/scripts.pory"
	goto_if_eq VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED, RockTunnel_B1F_EventScript_RanFromCelebi
# 107 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_CAUGHT_REGIROCK
# 108 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 109 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndRock
# 110 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 111 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 112 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 113 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 114 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 115 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 116 "data/maps/RockTunnel_B1F/scripts.pory"

# 117 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_DefeatedCelebi::
# 118 "data/maps/RockTunnel_B1F/scripts.pory"
	setflag FLAG_CAUGHT_REGIROCK
# 119 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 120 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndRock
# 121 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 122 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 123 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 124 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 125 "data/maps/RockTunnel_B1F/scripts.pory"
	goto EventScript_RemoveStaticMon
# 126 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 127 "data/maps/RockTunnel_B1F/scripts.pory"

# 128 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_RanFromCelebi::
# 129 "data/maps/RockTunnel_B1F/scripts.pory"
	setvar VAR_0x8004, SPECIES_REGIROCK
# 130 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 131 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndRock
# 132 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 133 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 134 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 135 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 136 "data/maps/RockTunnel_B1F/scripts.pory"
	goto EventScript_MonFlewAway
# 137 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 138 "data/maps/RockTunnel_B1F/scripts.pory"

# 139 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_NoRock::
# 140 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_NoRock
# 141 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 142 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 143 "data/maps/RockTunnel_B1F/scripts.pory"

# 144 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_End::
# 145 "data/maps/RockTunnel_B1F/scripts.pory"
	clearflag FLAG_ROCK_TRAINER
# 146 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EndRock
# 147 "data/maps/RockTunnel_B1F/scripts.pory"
	waitmessage
# 148 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_TO_BLACK
# 149 "data/maps/RockTunnel_B1F/scripts.pory"
	removeobject LOCALID_MIRAGE
# 150 "data/maps/RockTunnel_B1F/scripts.pory"
	fadescreen FADE_FROM_BLACK	
# 151 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 152 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 153 "data/maps/RockTunnel_B1F/scripts.pory"

# 154 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_EventScript_Regirock::
# 155 "data/maps/RockTunnel_B1F/scripts.pory"
	lock
# 156 "data/maps/RockTunnel_B1F/scripts.pory"
	faceplayer
# 157 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_Regirock, MSGBOX_NPC
# 158 "data/maps/RockTunnel_B1F/scripts.pory"
	release
# 159 "data/maps/RockTunnel_B1F/scripts.pory"
	end
# 160 "data/maps/RockTunnel_B1F/scripts.pory"

# 161 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_Regirock::
# 162 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "REGIROCK!$"
# 163 "data/maps/RockTunnel_B1F/scripts.pory"

# 164 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_NoEligiblePkmn::
# 165 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "You have not meet the requirements.\p"
# 166 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Come back when you do.$"
# 167 "data/maps/RockTunnel_B1F/scripts.pory"

# 168 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_RegiceCheck::
# 169 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Hello there {PLAYER}.\p"
# 170 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I am the Rocky Mirage Trainer.\p"
# 171 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Beat me and you shall face a\n"
# 172 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "special POKEMON.\p"
# 173 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "But first, I want to see a\n"
# 174 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "ANCIENT FISH,\l"
# 175 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "and knowledge on a STRONG MAN.$"
# 176 "data/maps/RockTunnel_B1F/scripts.pory"

# 177 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_Rock::
# 178 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "So, you wish to face me?$"
# 179 "data/maps/RockTunnel_B1F/scripts.pory"

# 180 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_YesRock::
# 181 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Very well! Prepare yourself!$"
# 182 "data/maps/RockTunnel_B1F/scripts.pory"

# 183 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_PostRock::
# 184 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "So you are worthy...$"
# 185 "data/maps/RockTunnel_B1F/scripts.pory"

# 186 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_RockPostBattle::
# 187 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Alright, you have bested me.\p"
# 188 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Be prepared to face REGIROCK!$"
# 189 "data/maps/RockTunnel_B1F/scripts.pory"

# 190 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_EndRock::
# 191 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Goodbye.$"
# 192 "data/maps/RockTunnel_B1F/scripts.pory"

# 193 "data/maps/RockTunnel_B1F/scripts.pory"
RockTunnel_B1F_Text_NoRock::
# 194 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Alright, take your time.$"
