CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon::
    .string "I found this most remarkable fossil\n"
    .string "inside MT. MOON.\p"
    .string "I think it's of a rare, prehistoric\n"
    .string "POKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_TeachMonMoveForMushroom::
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me TWO TINYMUSHROOMs,\n"
    .string "or a BIG MUSHROOM.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one POKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of MUSHROOMS!\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

CinnabarIsland_PokemonLab_Lounge_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

CinnabarIsland_PokemonLab_Lounge_Text_TeachWhichMove::
    .string "Which move should I teach?$"

CinnabarIsland_PokemonLab_Lounge_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

CinnabarIsland_PokemonLab_Lounge_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"

CinnabarIsland_PokemonLab_Lounge_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"

CinnabarIsland_PokemonLab_Lounge_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"

CinnabarIsland_PokemonLab_Lounge_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, I need a MUSHROOM.$"

CinnabarIsland_PokemonLab_Lounge_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

