# 1 "data/maps/MtMoonSquare/scripts.pory"

# 2 "data/maps/MtMoonSquare/scripts.pory"

# 3 "data/maps/MtMoonSquare/scripts.pory"
MtMoonSquare_MapScripts::
# 4 "data/maps/MtMoonSquare/scripts.pory"
	.byte 0
# 5 "data/maps/MtMoonSquare/scripts.pory"

# 6 "data/maps/MtMoonSquare/scripts.pory"
MtMoonSquare_EventScript_Clefairy::
# 7 "data/maps/MtMoonSquare/scripts.pory"
	msgbox MtMoonSquare_Text_Clefairy, MSGBOX_NPC
# 8 "data/maps/MtMoonSquare/scripts.pory"
	end
