Route19_Text_RichardIntro::
    .string "I have to exercise and warm up\n"
    .string "before going out for a swim.$"

Route19_Text_RichardDefeat::
    .string "All warmed up!$"

Route19_Text_RichardPostBattle::
    .string "Thanks, kid!\n"
    .string "I'm ready for a swim.$"

Route19_Text_ReeceIntro::
    .string "Wait! Slow down!\n"
    .string "You'll have a heart attack!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "That's chilly!$"

Route19_Text_ReecePostBattle::
    .string "Watch out for TENTACOOL.\n"
    .string "They sting so painfully.$"

Route19_Text_MatthewIntro::
    .string "I love swimming!\n"
    .string "What about you?$"

Route19_Text_MatthewDefeat::
    .string "Belly flop!$"

Route19_Text_MatthewPostBattle::
    .string "I can beat even marine POKéMON\n"
    .string "at swimming.$"

Route19_Text_DouglasIntro::
    .string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "I see a couple of islands over\n"
    .string "yonder!$"

Route19_Text_DavidIntro::
    .string "I tried diving for POKéMON, but it\n"
    .string "was a no-go.$"

Route19_Text_DavidDefeat::
    .string "Help!$"

Route19_Text_DavidPostBattle::
    .string "I guess you have to fish for sea\n"
    .string "POKéMON.$"

Route19_Text_TonyIntro::
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Traumatic!$"

Route19_Text_TonyPostBattle::
    .string "I'm looking at the sea to forget\n"
    .string "the bad thing that happened!$"

Route19_Text_AnyaIntro::
    .string "Oh, I just love your ride!\n"
    .string "Can I have it if I win?$"

Route19_Text_AnyaDefeat::
    .string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
    .string "It's still a long way to go to\n"
    .string "SEAFOAM ISLANDS…\p"
    .string "I want to go back to FUCHSIA…$"

Route19_Text_AliceIntro::
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"

Route19_Text_AliceDefeat::
    .string "Shocker!$"

Route19_Text_AlicePostBattle::
    .string "My boyfriend wanted to swim to\n"
    .string "SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro::
    .string "Ahoy, there!\n"
    .string "These waters are treacherous!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Dangerous!$"

Route19_Text_AxlePostBattle::
    .string "M-my legs! They cramped up!\n"
    .string "Glub, glub…$"

Route19_Text_ConnieIntro::
    .string "I swam here with my friends…\n"
    .string "I'm tired…$"

Route19_Text_ConnieDefeat::
    .string "I'm exhausted…$"

Route19_Text_ConniePostBattle::
    .string "If I were to ride a POKéMON on\n"
    .string "the sea, I'd like a LAPRAS.\p"
    .string "LAPRAS is so big, I bet it\n"
    .string "would keep me dry on water.$"

Route19_Text_RouteSign::
    .string "SEA ROUTE 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro::
    .string "LIA: I'm looking after my brother.\n"
    .string "He just became a TRAINER.$"

Route19_Text_LiaDefeat::
    .string "LIA: That's no way to treat my\n"
    .string "little brother!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Do you have a younger\n"
    .string "brother?\p"
    .string "I hope you're teaching him all\n"
    .string "sorts of things.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: I want to battle together\n"
    .string "with my little brother.\p"
    .string "Don't you have two POKéMON?$"

Route19_Text_LucIntro::
    .string "LUC: My big sis taught me how\n"
    .string "to swim and train POKéMON.$"

Route19_Text_LucDefeat::
    .string "LUC: Oh, wow!\n"
    .string "Someone tougher than my big sis!$"

Route19_Text_LucPostBattle::
    .string "LUC: My big sis is strong and nice.\n"
    .string "I think she's awesome!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: I don't want to if I can't\n"
    .string "battle you with my big sis.\p"
    .string "Don't you have two POKéMON?$"


Route19_Text_CongratsYouveWon::
    .string "This HM is useless!\p"
    .string "There aren't any DIVE spots around\n"
    .string "KANTO, nor are there any in the\l"
    .string "SEVII ISLANDS!\p"
    .string "I'm not interested in battling,\n"
    .string "so take it!$"

Route19_Text_ReceivedHM08FromDiveGuy::
    .string "{PLAYER} received HM08!$"

Route19_Text_ReceivedHM07FromDiveGuy::
    .string "{PLAYER} received HM07!$"

Route19_Text_ExplainDive::
    .string "HM08 is DIVE.\p"
    .string "Your POKéMON hide in water one\n"
    .string "turn, before emerging and dealing\l"
    .string "damage on the next.\p"
    .string "Hopefully you can find a use for\n"
    .string "this HM in battle!$"

Route19_Text_ExplainWaterfall::
    .string "Oh, also…\p"
    .string "I have yet another utterly\n"
    .string "worthless HM to give you!$"

Route19_Text_ExplainWaterfall2::
    .string "HM07 is WATERFALL.\p"
    .string "Your POKéMON rides up a stream of\n"
    .string "water and charges at the foe,\l"
    .string "dealing damage with a chance to\l"
    .string "make the opponent flinch!$"

Route19_Text_DontHaveRoomForPrize::
    .string "You don't have room for this\n"
    .string "useless HM!$"

