# 1 "data/maps/CeladonCity_Diglett/scripts.pory"

# 2 "data/maps/CeladonCity_Diglett/scripts.pory"
CeladonCity_Diglett_MapScripts::
# 3 "data/maps/CeladonCity_Diglett/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Diglett/scripts.pory"

# 5 "data/maps/CeladonCity_Diglett/scripts.pory"

# 6 "data/maps/CeladonCity_Diglett/scripts.pory"
CeladonCity_Diglett_EventScript_Hiker::
# 7 "data/maps/CeladonCity_Diglett/scripts.pory"
	lock
# 8 "data/maps/CeladonCity_Diglett/scripts.pory"
	faceplayer
# 9 "data/maps/CeladonCity_Diglett/scripts.pory"
	msgbox CeladonCity_Diglett_Text_Hiker, MSGBOX_NPC
# 10 "data/maps/CeladonCity_Diglett/scripts.pory"
	return
# 11 "data/maps/CeladonCity_Diglett/scripts.pory"
	end
# 12 "data/maps/CeladonCity_Diglett/scripts.pory"

# 13 "data/maps/CeladonCity_Diglett/scripts.pory"
CeladonCity_Diglett_EventScript_GuardHater::
# 14 "data/maps/CeladonCity_Diglett/scripts.pory"
	lock
# 15 "data/maps/CeladonCity_Diglett/scripts.pory"
	faceplayer
# 16 "data/maps/CeladonCity_Diglett/scripts.pory"
	msgbox CeladonCity_Diglett_Text_GuardHater, MSGBOX_NPC
# 17 "data/maps/CeladonCity_Diglett/scripts.pory"
	return
# 18 "data/maps/CeladonCity_Diglett/scripts.pory"
	end
