CeladonCity_Diglett_Text_Hiker::
    .string "Those guards have been blocking\n"
    .string "the way for a while now.\p"
    .string "I have no idea why.\p"
    .string "Me and my friend are pretty\n"
    .string "ticked off about it.\p"
    .string "Times like this are why we\n"
    .string "built the UNDERGROUND PATH!$"


CeladonCity_Diglett_Text_GuardHater::
    .string "I've had it with those guards!\n"
    .string "They're always in the way.\p"
    .string "If they don't move soon, I'll\n"
    .string "have to show them a thing or two!$"

CeladonCity_Diglett_Text_GuardHaterThanks::
    .string "You opened the gates?\n"
    .string "Finally! Now I don't have to\l"
    .string "deal with the guards!\l"
    .string "You can have this as a thanks!\p"

CeladonCity_Diglett_Text_GuardHaterThanks2::
    .string "We found that while digging\n"
    .string "the UNDERGROUND PATH.\p"
    .string "A huge rock also fell and\n"
    .string "blocked the way.\p"
    .string "Good thing the gates are open!$"
