CeladonCity_Diglett_Text_Hiker::
    .string "Those Guards have\n"
    .string "closed the entrances for a\l"
    .string "while.\p"
    .string "I have no idea why.\p"
    .string "My Friend isn't liking.\n"
    .string "it either.\p"
    .string "It's why I built.\n"
    .string "That Underground Tunnel.$"


CeladonCity_Diglett_Text_GuardHater::
    .string "Darn Guards,\n"
    .string "they just want to close\l"
    .string "everything huh?\p"
    .string "Well I'll show them!\p"
    .string "Those guards will go.\n"
    .string "Down!$"

