CeladonCity_Diglett_Text_Hiker::
    .string "Those Guards have\n"
    .string "closed the entrances for a\l"
    .string "while.\p"
    .string "I have no idea why.\p"
    .string "My Friend isn't liking.\n"
    .string "it either.\p"
    .string "It's why I built.\n"
    .string "That Underground Tunnel.$"


CeladonCity_Diglett_Text_GuardHater::
    .string "Darn Guards,\n"
    .string "they just want to close\l"
    .string "everything huh?\p"
    .string "Well I'll show them!\p"
    .string "Those guards will go.\n"
    .string "Down!$"

CeladonCity_Diglett_Text_GuardHaterThanks::
    .string "You Opened The Gates?\n"
    .string "Thank You! Now I don't\l"
    .string "have to fight the Guards!\l"
    .string "You can have this as a thanks!\p"

CeladonCity_Diglett_Text_GuardHaterThanks2::
    .string "We got that while digging\n"
    .string "The Tunnel.\p"
    .string "A Big Rock also fall and Blocked\n"
    .string "So Good thing the gates opened!$"
