FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "You travel all over the place,\n"
    .string "don't you?\p"
    .string "You're not driving your POKéMON\n"
    .string "too harshly, are you?\p"
    .string "Let me take a look.\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Ah, hmm…\n"
    .string "I see, I see…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Oh, impressive.\n"
    .string "You treat your POKéMON right.\p"
    .string "I think you can be entrusted with\n"
    .string "this.\p"
    .string "Please, I'd like you to have this.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} received an EGG\n"
    .string "from the man!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Unfortunately, you don't have\n"
    .string "space for this in your party.\p"
    .string "You'd better come back for it\n"
    .string "another time.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "I received that EGG while I was\n"
    .string "traveling.\p"
    .string "I'm glad I met someone like you.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Oh, hello.\n"
    .string "That's a cute {STR_VAR_2}.\p"
    .string "Seeing it reminds me of a sweet \n"
    .string "little girl I met while traveling.\p"
    .string "She was gently grooming POKéMON…\n"
    .string "She was a little angel.\p"
    .string "That little girl's name…\n"
    .string "I think it was DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "This is an excellent environment\n"
    .string "for raising POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "Your POKéMON are growing up\n"
    .string "admirably well!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "You know, I think you have the\n"
    .string "talent to be a good BREEDER.$"

FiveIsland_WaterLabyrinth_Text_Falkner::
    .string "Have you seen the skies today?\n"  
    .string "They soar above the endless\l"  
    .string "waters of the ocean.\p"  
    .string "Oh, wait, you're the\n"  
    .string "KANTO CHAMPION?\p"  
    .string "I'm a GYM LEADER from JOHTO who\n"
    .string "specializes in the FLYING type.\p"  
    .string "I'd like to test your mettle!$"  

FiveIsland_WaterLabyrinth_Text_FalknerDefeat::
    .string "You are a soaring TRAINER!$"  

FiveIsland_WaterLabyrinth_Text_FalknerPostBattle::
    .string "I'm hoping to retire from being\n"  
    .string "a GYM LEADER soon so I can\l"  
    .string "travel the world.\p"  
    .string "My son is eager to take the mantle.\n"  
    .string "You might challenge him one day!$"  

FiveIsland_WaterLabyrinth_Text_NoFalkner::
    .string "Oh? Then perhaps another time?$"

FiveIsland_WaterLabyrinth_Text_YesFalkner::
    .string "Let me see your POKéMON soar!$"

FiveIsland_WaterLabyrinth_Text_RematchFalkner::
    .string "You wish to battle again?\p"
    .string "Very well, I accept.$"

FiveIsland_WaterLabyrinth_Text_RematchFalknerDefeat::
    .string "You are a soaring TRAINER!$" 

FiveIsland_WaterLabyrinth_Text_YesRematchFalkner::
    .string "Let me see your POKéMON soar!$"

FiveIsland_WaterLabyrinth_Text_RematchFalknerPostBattle::
    .string "I'm hoping to retire from being\n"  
    .string "a GYM LEADER soon so I can\l"  
    .string "travel the world.\p"  
    .string "My son is eager to take the mantle.\n"  
    .string "You might challenge him one day!$"  
