Route23_Text_VictoryRoadGateSign::
    .string "VICTORY ROAD GATE -\n"
    .string "POKéMON LEAGUE$"

Route23_Text_RestHouse::
    .string "VICTORY ROAD -\n"
    .string "REST HOUSE$"

Route23_Text_Clerk::
    .string "Oh, hi there, challenger!\p"
    .string "I have a permit to sell\n"
    .string "POKéMON MART items here.\p"
    .string "Also, feel free to visit\n"
    .string "our REST HOUSE to the\l"
    .string "right next door!$"

Route23_Text_NotReady::
    .string "Sorry, our services\n"
    .string "are closed right now,\l"
    .string "as we're fixing a leak.\p"
    .string "Though since the\n"
    .string "VIRIDIAN GYM LEADER is\l"
    .string "back, we've gotta be\l"
    .string "quick in fixing it!$"
