Route23_Text_VictoryRoadGateSign::
    .string "VICTORY ROAD GATE -\n"
    .string "POKéMON LEAGUE$"

Route23_Text_RestHouse::
    .string "VICTORY ROAD -\n"
    .string "REST HOUSE$"

Route23_Text_Clerk::
    .string "Oh Hi there Challenger!\p"
    .string "I've got a permit to\n"
    .string "sell PokeMart Stuff Here!\p"
    .string "You can also go right\n"
    .string "To rest at Me and My Wife's\n"
    .string "Rest House!$"
