Route23_Text_VictoryRoadGateSign::
    .string "VICTORY ROAD GATE -\n"
    .string "POKéMON LEAGUE$"

Route23_Text_RestHouse::
    .string "VICTORY ROAD -\n"
    .string "REST HOUSE$"

Route23_Text_Clerk::
    .string "Oh hi there challenger!\p"
    .string "I've got a permit to\n"
    .string "sell PokeMart Stuff Here!\p"
    .string "You can also go right\n"
    .string "to rest at me and my Wife's\l"
    .string "REST HOUSE!$"

Route23_Text_NotReady::
    .string "Sorry, our services\n"
    .string "are closed right now as\l"
    .string "we are fixing a Leak.\p"
    .string "Although since the\n"
    .string "VIRIDIAN GYM LEADER is\l"
    .string "back, we gotta be quick\l"
    .string "fixing it!$"
