PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!\p"
	.string "If your confused on what version\n"
	.string "we are on,\l"
	.string "we are on VERSION 1.55!\p"
	.ifdef FIRERED
	.string "POKEMON FIRE RED: REIGNITED!$"
	.else
	.ifdef LEAFGREEN
	.string "POKEMON LEAF GREEN: REGROWN!$"
	.endif
	.endif

PalletTown_PlayersHouse_2F_Text_Normal::
	.string "DIFFICULTY: NORMAL.$"

PalletTown_PlayersHouse_2F_Text_Hard::
	.string "DIFFICULTY: HARD.$"

PalletTown_PlayersHouse_2F_Text_Hardcore::
	.string "DIFFICULTY: HARDCORE.$"
