OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Here we are!\n"
    .string "This is ONE ISLAND.\p"
    .string "There are several islands around\n"
    .string "here, and this is one of them.\p"
    .string "My friend CELIO sent the boat to\n"
    .string "fetch me here.\p"
    .string "He's in charge of the island's PC\n"
    .string "network by his lonesome.\p"
    .string "…Why am I telling you this now?\n"
    .string "Let's just go see CELIO!$"

Text_WhereDoYouWantToSail::
    .string "Ahoy, there!\n"
    .string "Where do you want to sail?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Here we are on an island smack in\n"
    .string "the middle of nowhere.\p"
    .string "We're lucky to have an upstanding\n"
    .string "young man like CELIO here.\p"
    .string "My granddaughter was in a tizzy\n"
    .string "over CELIO's friend.\p"
    .string "Something about a famous\n"
    .string "POKéMANIAC?\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we now have PC linkage\n"
    .string "with people in KANTO.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we finally have PC linkage\n"
    .string "with people in HOENN.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man.\p"
    .string "He would make a fine husband for\n"
    .string "my granddaughter!$"

OneIsland_Text_IslandSign::
    .string "ONE ISLAND\n"
    .string "Friends Gather at Knot Island$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Expanding the POKéMON World!\n"
    .string "POKéMON NET CENTER$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hi, sight-seeing, are you?\n"
    .string "Isn't the warm climate here great?$"

OneIsland_Text_Brock::
	.string "Oh, hi there {PLAYER},\n"
	.string "I've heard that you've\l"
	.string "helped my friend power\l"
	.string "his machine,\l"
	.string "so I came here immediately!\p"
	.string "Great job on becoming\n"
	.string "CHAMPION as well as\l"
	.string "defeating TEAM ROCKET.\p"
	.string "Oh by the way.\p"
	.string "The SEVII LEADERS are here!\p"
	.string "Their like GYM LEADERS of\n"
	.string "their respective islands.\p"
	.string "If you beat the first six,\n"
	.string "you get to fight the\l"
	.string "SUPREME LEADER on SEVEN ISLAND.\p"
	.string "Our ELITE FOUR is still\n"
	.string "stronger, but they should\l"
	.string "give you good training\l"
	.string "if you want to fight them\l"
	.string "at their strongest!\p"
	.string "Some merchants may also\n"
	.string "appear to people of\l"
	.string "high achievement.\p"
	.string "Well, I'll go meet CELIO\n"
	.string "and then leave.\l"
	.string "Good luck on your journey!$"
 
