LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "Memorial services are held in\n"
    .string "POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "POKéMON that the ROCKETS killed.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"

LavenderTown_Text_Karen::
    .string "Strong POKéMON, weak POKéMON…\n"
    .string "I prefer to use my favourites.\p"
    .string "What about you, CHAMPION?\p"
    .string "I'm training to become an\n"
    .string "ELITE FOUR member myself.\p"
    .string "I'll show you what I've been\n"
    .string "working on!$"

LavenderTown_Text_KarenDefeat::
    .string "Seems CHAMPION-level to me!$"

LavenderTown_Text_KarenPostBattle::
    .string "What a great battle!\p"
    .string "Truly, you feel for POKéMON!\p"
    .string "I want you to have this gift.\n"
    .string "It'll help you find even more!$"

LavenderTown_Text_NoKaren::
    .string "Not interested, huh?$"

LavenderTown_Text_YesKaren::
    .string "Alright, CHAMPION…\p"
    .string "Let's battle!$"

LavenderTown_Text_RematchKaren::
    .string "This town is a special place\n"
    .string "for both people and POKéMON.\l"
    .string "I'm visiting to learn more.\p"
    .string "Do you want to rematch?$"

LavenderTown_Text_RematchKarenDefeat::
    .string "Seems you've honed your style!$"

LavenderTown_Text_PostRematchKaren::
    .string "What a great battle!\p"
    .string "Truly, you feel for POKéMON!$"

