LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "Memorial services are held in\n"
    .string "POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "POKéMON that the ROCKETS killed.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"

LavenderTown_Text_Karen::
    .string "Strong Pokemon, Weak Pokemon\n"
    .string "or your Favorites?\p"
    .string "Which one did you used Champion?\p"
    .string "I prefer the latter.\p"
    .string "I'm training to become a\n"
    .string "ELITE FOUR Member myself.\p"
    .string "I hope a battle could show you\n"
    .string "my strength!$"

LavenderTown_Text_KarenDefeat::
    .string "Seems Champion Level to me!$"

LavenderTown_Text_KarenPostBattle::
    .string "What a great battle!\p"
    .string "Truly you feel for Pokemon!.\p"
    .string "I want you to have this gift\n"
    .string "that can help you meet more!\l"
    .string "pokemon!$"

LavenderTown_Text_NoKaren::
    .string "Not Interested huh?$"

LavenderTown_Text_YesKaren::
    .string "Looks like i'm in for much!\p"
    .string "Let's Battle!$"

LavenderTown_Text_RematchKaren::
    .string "I'm just visiting this town\n"
    .string "as to understand more of\l"
    .string "pokemon!\p"
    .string "You want a rematch?$"

LavenderTown_Text_RematchKarenDefeat::
    .string "Seems like you set your style!$"

LavenderTown_Text_PostRematchKaren::
    .string "What a great battle!\p"
    .string "Truly you feel for Pokemon!$"

