Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"

Route2_EastBuilding_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with\n"
    .string "HM06 ROCK SMASH,\l"
	.string "and if you're looking for the AIDE\l"  
	.string "with FLASH, he's on ROUTE 10.\p"  
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route2_EastBuilding_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received HM06 ROCK SMASH\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainEverstone::
    .string "ROCK SMASH can be used to break\n"
    .string "smashable rocks, and you can\l"
    .string "sometimes encounter wild POKéMON\l"
    .string "in the rubble.\p" 
    .string "You'll need LT SURGE's BADGE\n"
    .string "to use ROCK SMASH.$"
