CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"

CeruleanCave_B1F_Text_SmithIntro::
    .string "Hey, what's up?\p"  
    .string "Show me how much zest\n"  
    .string "you've got!$"  

CeruleanCave_B1F_Text_SmithDefeat::
    .string "Wow! You've got zest!$"  

CeruleanCave_B1F_Text_SmithPostBattle::
    .string "You should have no problem\n"  
    .string "getting through this cave.\p"  
    .string "Good luck, nerd!$"  

