CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"

CeruleanCave_B1F_Text_SmithIntro::
    .string "Hey, what's up?\p"  
    .string "Show me how much zest\n"  
    .string "you've got!$"  

CeruleanCave_B1F_Text_SmithDefeat::
    .string "Wow! You've got zest!$"  

CeruleanCave_B1F_Text_SmithPostBattle::
    .string "What zest! You should be able\n"  
    .string "to handle yourself in this cave.\p"
    .string "Good luck, nerd!\p"
    .string "And I hope you're not using\n"  
    .string "GYARADOS - I'm starting to\l"  
    .string "hate that POKéMON.$"  

