CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"

CeruleanCave_B1F_Text_SmithIntro::
    .string "Hey, what's up?\p"  
    .string "Show me how much zest\n"  
    .string "you've got!$"  

CeruleanCave_B1F_Text_SmithDefeat::
    .string "Wow!You've got zest!\n"  
    .string "I love to see that.$"  


CeruleanCave_B1F_Text_SmithPostBattle::
    .string "What zest!You should be able\n"  
    .string "to handle yourself in this cave!\p"  
    .string "Good luck, nerd!$"  

