PowerPlant_Text_CraigIntro::
    .string "I'm trying to complete my\n"  
    .string "POKéDEX, for a game I'm\l"  
    .string "making based on POKéMON.\p"  
    .string "How about this…\p"  
    .string "We battle, winner gets the\n"  
    .string "bird.$"  


PowerPlant_Text_CraigDefeat::
    .string "This is good data!$"  

PowerPlant_Text_CraigPostBattle::
    .string "Can I see the POKéDEX entry\n"  
    .string "once you catch it?$"  

