PowerPlant_Text_CraigIntro::
    .string "I'm trying to complete my POKéDEX,\n"  
    .string "for a game I'm making \l"  
    .string "based on POKéMON.\p"  
    .string "How about this…\p"  
    .string "We battle,\n"  
    .string "winner gets the bird.$"  


PowerPlant_Text_CraigDefeat::
    .string "This is good data!$"  

PowerPlant_Text_CraigPostBattle::
    .string "Can I see the POKéDEX entry\n"  
    .string "once you catch it?$"  

