PowerPlant_Text_CraigIntro::
    .string "I'm trying to complete my\n"  
    .string "POKÉDEX, for a game I'm\l"  
    .string "making based on POKÉMON.\p"  
    .string "How about this…\p"  
    .string "We battle, winner gets the\n"  
    .string "bird.$"  


PowerPlant_Text_CraigDefeat::
    .string "This is good data!\p"  
    .string "I can use this.$"  

PowerPlant_Text_CraigPostBattle::
    .string "Can I see the POKÉDEX entry\n"  
    .string "once you catch it?$"  

