SixIsland_DottedHole_B2F_Text_Speedy::
    .string "Bro how does this puzzle work?\p"  
    .string "I have been trying to get though\n"  
    .string "this now open cave for like a hour,\l"  
    .string "I don't even know if there is like,\l"  
    .string "500 floors?\p"  
    .string "Well I guess I can tell you I'm\n"  
    .string "sort of a Champion of this place.\p"  
    .string "The strongest of this Island!\p"  
    .string "If you want, We could go for\n"  
    .string "a Speedy Battle!$"  

SixIsland_DottedHole_B2F_Text_SpeedyDefeat::
    .string "WAAAAAAAA!$"

SixIsland_DottedHole_B2F_Text_SpeedyPostBattle::
    .string "What an ELECTRODE!\p"
    .string "You're The KANTO CHAMPION!\P"
    .string "I guess that makes this\n"
    .string "Cave a little bit Better!$"

SixIsland_DottedHole_B2F_Text_NoSpeedy::
    .string "Not ready huh?$"

SixIsland_DottedHole_B2F_Text_YesSpeedy::
    .string "Alright. Let's do This!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedy::
    .string "Bro I'm still stuck on this.\p"  
    .string "Probably better to do\n"  
    .string "something else.\p"  
    .string "Want another battle?$"  

SixIsland_DottedHole_B2F_Text_RematchSpeedyDefeat::
    .string "WAAAAAAAA!$"

SixIsland_DottedHole_B2F_Text_YesRematchSpeedy::
    .string "Alright. Let's do This!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedyPostBattle::
    .string "Maybe I'll solve this some day.$"
