SixIsland_DottedHole_B2F_Text_Speedy::
    .string "Yo, how does this puzzle work?\p"  
    .string "I've been trying to get though\n"  
    .string "this cave for what seems like\l"  
    .string "an hour…\p"  
    .string "There must be something like\n"
    .string "500 floors!\p"
    .string "Well, I'm sort of the CHAMPION\n"  
    .string "of this place.\p"  
    .string "The strongest of this ISLAND!\p"  
    .string "If you want, We could go for\n"  
    .string "a speedy battle!$"  

SixIsland_DottedHole_B2F_Text_SpeedyDefeat::
    .string "Waaaaaaah!$"

SixIsland_DottedHole_B2F_Text_SpeedyPostBattle::
    .string "What an ELECTRODE!\p"
    .string "You're the KANTO CHAMPION,\n"
    .string "aren't you?\p"
    .string "I guess you've helped make this\n"
    .string "cave a little more bearable!$"

SixIsland_DottedHole_B2F_Text_NoSpeedy::
    .string "Not ready, huh?$"

SixIsland_DottedHole_B2F_Text_YesSpeedy::
    .string "Alright. Let's do this!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedy::
    .string "Yo, I'm still stuck on this.\p"  
    .string "I'd rather be doing something\n"  
    .string "else… such as battling!\p"  
    .string "Are you up for another round?$"  

SixIsland_DottedHole_B2F_Text_RematchSpeedyDefeat::
    .string "Waaaaaaah!$"

SixIsland_DottedHole_B2F_Text_YesRematchSpeedy::
    .string "Alright. Let's do this!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedyPostBattle::
    .string "Maybe I'll figure this out some day…$"
