SixIsland_DottedHole_B2F_Text_Speedy::
    .string "Speedy Placeholder!$"


SixIsland_DottedHole_B2F_Text_SpeedyDefeat::
    .string "Speedy Placeholder!$"

SixIsland_DottedHole_B2F_Text_SpeedyPostBattle::
    .string "Speedy Placeholder!$"

SixIsland_DottedHole_B2F_Text_NoSpeedy::
    .string "Speedy Placeholder!$"

SixIsland_DottedHole_B2F_Text_YesSpeedy::
    .string "Speedy Placeholder!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedy::
    .string "Speedy Rematch Placeholder!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedyDefeat::
    .string "Speedy Rematch Placeholder!$"

SixIsland_DottedHole_B2F_Text_YesRematchSpeedy::
    .string "Speedy Rematch Placeholder!$"

SixIsland_DottedHole_B2F_Text_RematchSpeedyPostBattle::
    .string "Speedy Rematch Placeholder!$"
