Text_RockSlideTeach::
    .string "When you're up on a rocky mountain\n"
    .string "like this, rockslides are a threat.\p"
    .string "Can you imagine?\n"
    .string "Boulders tumbling down on you?\p"
    .string "That'd be, like, waaaaaaaaaaah!\n"
    .string "Total terror!\p"
    .string "You don't seem to be scared.\n"
    .string "Want to try using ROCK SLIDE?$"

Text_RockSlideDeclined::
    .string "Oh, so you are scared after all.$"

Text_RockSlideWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "It might be scary to use it in this\n"
    .string "tunnel…$"

Text_RockSlideReteach::
    .string "You really aren't afraid of rockslides\n"
    .string "if you're here spelunking again.\p"
    .string "I can teach you ROCK SLIDE\n"
    .string "once more if you can pay ¥50000.$"
Text_RockSlideReteach2::
    .string "Would you like me to teach\n"
    .string "ROCK SLIDE?$"
Text_RockSlideNotEnoughMoney::
    .string "Supplies for exploring caves\n"
    .string "don't come cheap.\p"
    .string "If I don't charge for my services,\n"
    .string "I can't afford to keep exploring!\p"
    .string "If you want to learn ROCK SLIDE,\n"
    .string "come back with ¥50000.$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Boulders might change the\n"
    .string "flow of water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "DANGER\n"
    .string "Fast current!$"

SeafoamIslands_B4F_Text_WeebraIntro::
    .string "You gotta be pretty strong\n"  
    .string "to get this far, huh?\p"  
    .string "Then I guess we don't gotta\n"  
    .string "pull any punches.$"  

SeafoamIslands_B4F_Text_WeebraDefeat::
    .string "Nice moves!\p"  
    .string "I almost got off my 'Essence\n"  
    .string "of Beast Style' too!$"  

SeafoamIslands_B4F_Text_WeebraPostBattle::
    .string "Honestly I prefer my team\n"  
    .string "fresh, never frozen,\l"  
    .string "but you do you, bro!$"  

SeafoamIslands_B4F_Text_Slowpoke::
    .string "SLOWPOKE!$"
