FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Keep your filthy hands\n"
    .string "off the POKéMON in the cave!\p"
    .string "Do as I say, or you'll have me to\n"
    .string "answer to!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Aww, shut it, lady, and leave\n"
    .string "us be.\p"
    .string "Don't let your glasses get all\n"
    .string "steamed up!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "What are you doing here?\p"
    .string "No, we can catch up later.\n"
    .string "Right now, I need your help.\p"
    .string "Help me kick these poachers out\n"
    .string "before they do anything else.\p"
    .string "They've been catching POKéMON\n"
    .string "here, then selling them off!\p"
    .string "Are you ready?\n"
    .string "You take that one, please!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "W-what?!\p"
    .string "Who says we can't do what we want\n"
    .string "with the POKéMON we catch?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "We didn't plan on this!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Humph.\n"
    .string "So despicably weak.\p"
    .string "You!\n"
    .string "Tell me!\p"
    .string "Where have you taken the captured\n"
    .string "POKéMON?\p"
    .string "I'm smashing your ring once and\n"
    .string "for all!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "N-no way!\n"
    .string "I'm not telling you that!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: If you won't confess,\n"
    .string "we'll deep-freeze you.\p"
    .string "My LAPRAS is furious for what\n"
    .string "you've done to its friends.\p"
    .string "Go, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawaah! Okay!\n"
    .string "I'll talk!\p"
    .string "The POKéMON are in the ROCKET\n"
    .string "WAREHOUSE on FIVE ISLAND.\p"
    .string "There! I said it!\n"
    .string "We'll be going now!\p"
    .string "…But I doubt you'll ever make it\n"
    .string "into the ROCKET WAREHOUSE!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, thank you.\n"
    .string "But this is awful…\p"
    .string "I was born and raised here on\n"
    .string "these islands.\p"
    .string "I had no idea that those horrible\n"
    .string "criminals were loose here…$"

FourIsland_IcefallCave_Back_Text_Pryce::  
    .string "This back side of this cave\n"  
    .string "is truly magnificent.\p"  
    .string "As the Ice Type GYM Leader,\n"  
    .string "PRYCE, I won't hold back\l"  
    .string "against the CHAMPION!\p"  
    .string "If you are willing!$"  

FourIsland_IcefallCave_Back_Text_PryceDefeat::  
    .string "Kids these days!\n"  
    .string "Stronger than ever!$"  

FourIsland_IcefallCave_Back_Text_PrycePostBattle::  
    .string "Incredible! Expected from a\n"  
    .string "CHAMPION.\p"  
    .string "I hope you can protect us\n"  
    .string "from dangers lurking ahead.\p"  
    .string "I'm running out of time.$"  

FourIsland_IcefallCave_Back_Text_NoPryce::  
    .string "Maybe some other time.$"  

FourIsland_IcefallCave_Back_Text_YesPryce::  
    .string "Alright, alright.\p"  
    .string "Let's battle!$"  

FourIsland_IcefallCave_Back_Text_RematchPryce::  
    .string "A rematch?\p"  
    .string "Guess you just want to\n"  
    .string "battle, CHAMPION!$"  

FourIsland_IcefallCave_Back_Text_RematchPryceDefeat::  
    .string "Kids these days!\n"  
    .string "Stronger than ever!$"  

FourIsland_IcefallCave_Back_Text_YesRematchPryce::  
    .string "Alright, alright.\p"  
    .string "Let's battle!$"  

FourIsland_IcefallCave_Back_Text_RematchPrycePostBattle::  
    .string "Incredible! Expected from a\n"  
    .string "CHAMPION.\p"  
    .string "I hope you can protect us\n"  
    .string "from dangers lurking ahead.\p"  
    .string "I'm running out of time.$"  
