SevenIsland_TanobyRuins_MoneanChamber_Text_Armstrong::
    .string "Armstrong Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongDefeat::
    .string "Armstrong Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongPostBattle::
    .string "Armstrong Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_NoArmstrong::
    .string "Armstrong Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesArmstrong::
    .string "Armstrong Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrong::
    .string "Armstrong Rematch Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongDefeat::
    .string "Armstrong Rematch Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesRematchArmstrong::
    .string "Armstrong Rematch Placeholder!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongPostBattle::
    .string "Armstrong Rematch Placeholder!$"

