SevenIsland_TanobyRuins_MoneanChamber_Text_Armstrong::
	.string "Hmmm, how powerful do you\n"
	.string "reckon the POKEMON here must\l"
	.string "be?\p"
	.string "Would they be strong enough\n"
	.string "to take down a whole set of\l"
	.string "islands? Who knows.\p"
	.string "All I know is that I'm the\n"
	.string "strongest, not only of SEVEN\l"
	.string "ISLAND, but of the SEVII's\l"
	.string "as a whole.\p"
	.string "A Master they call it.\p"
	.string "I believe strength should\n"
	.string "be what allows us to raise\l"
	.string "lands to their greatest,\p"
	.string "prevent evil organizations\n"
	.string "from taking over, and bring\l"
	.string "order to all.\p"
	.string "Wouldn't you agree,\n"
	.string "KANTO CHAMPION?\p"
	.string "It seems like you're also\n"
	.string "here for a battle.\p"
	.string "I will grant it, if you wish\n"
	.string "to face strength itself.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongDefeat::
    .string "Great Job CHAMPION.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongPostBattle::
	.string "Seems like you've shown me\n"
	.string "what true strength really\l"
	.string "is.\p"
	.string "You are truly one of the\n"
	.string "greatest trainers I've seen\l"
	.string "of all time.\p"
	.string "But you still have more to\n"
	.string "face, such as the KANTO\l"
	.string "ELITE FOUR at their\l"
	.string "strongest...\p"
	.string "And a certain retired\n"
	.string "TRAINER.\p"
	.string "Good luck, {PLAYER}.$"
	.string "And I'll like to give\n"
	.string "You this.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongPostBattle2::
	.string "That ticket allows you to go\n"  
	.string "to a special area.\p"  
	.string "It was given to me, but I just\n"  
	.string "kept it until I found someone\n"  
	.string "worthy, like you.\p"  
	.string "Also, I'll let you access our\n"  
	.string "secret merchant on Five Island.\p"  
	.string "He's got some great stuff\n"  
	.string "to sell!$"  

SevenIsland_TanobyRuins_MoneanChamber_Text_NoArmstrong::
    .string "I guess you're not Ready.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesArmstrong::
    .string "Get ready to see what\n"
    .string "True Strength Is!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrong::
    .string "Ah, you're back for more!\n"
    .string "Needed some more Training Huh?$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongDefeat::
    .string "Great Job Again, CHAMPION$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesRematchArmstrong::
    .string "Get ready to see what\n"
    .string "True Strength Is!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongPostBattle::
    .string "Great to see you still\n"
    .string "Great Shape!\p"
    .string "Continue to Grew Further Than\n"
    .string "Anyone can Imagine!$"

