SevenIsland_TanobyRuins_MoneanChamber_Text_Armstrong::
	.string "Hmmm, how powerful do you think\n"
	.string "the POKéMON here must be?\p"
	.string "Would they be strong enough\n"
	.string "to take down a whole island?\l"
	.string "Who's to say.\p"
	.string "All I know is that I'm the\n"
	.string "strongest, not only of SEVEN\l"
	.string "ISLAND, but of all the SEVII\l"
	.string "ISLANDS as a whole.\p"
	.string "A MASTER, they call it.\p"
	.string "I believe strength should\n"
	.string "be what allows us to raise\l"
	.string "lands to their greatest,\p"
	.string "prevent evil organizations\n"
	.string "from taking over, and bring\l"
	.string "order to all.\p"
	.string "Wouldn't you agree,\n"
	.string "KANTO CHAMPION?\p"
	.string "It seems like you're also\n"
	.string "here for a battle.\p"
	.string "I will grant it, if you wish\n"
	.string "to face strength itself.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongDefeat::
    .string "Great job, CHAMPION.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongPostBattle::
	.string "Seems like you've shown me\n"
	.string "what true strength really is\p"
	.string "You are one of the greatest\n"
	.string "trainers I've ever seen.\p"
	.string "But you still have more to\n"
	.string "face, such as the KANTO\l"
	.string "ELITE FOUR at their\l"
	.string "strongest…\p"
	.string "And a certain retired\n"
	.string "TRAINER.\p"
	.string "Good luck, {PLAYER}\n"
	.string "And take this, as well.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_ArmstrongPostBattle2::
	.string "That ticket allows you to go\n"  
	.string "to a special area.\p"  
	.string "It was given to me, but I've\n"  
	.string "been waiting to give it to\n"  
	.string "someone worthy, like you.\p"  
	.string "Also, I'll let you access our\n"  
	.string "secret merchant on FIVE ISLAND.\p"  
	.string "He's got some great stuff\n"  
	.string "to sell!$"  

SevenIsland_TanobyRuins_MoneanChamber_Text_NoArmstrong::
    .string "I guess you're not ready.$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesArmstrong::
    .string "Get ready to know the\n"
    .string "true meaning of strength!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrong::
    .string "Ah, you're back for more!\n"
    .string "Need some more training?$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongDefeat::
    .string "Great job again, CHAMPION!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_YesRematchArmstrong::
    .string "Get ready to know the\n"
    .string "true meaning of strength!$"

SevenIsland_TanobyRuins_MoneanChamber_Text_RematchArmstrongPostBattle::
    .string "Good to see you're still\n"
    .string "in great shape!\p"
    .string "Keep going, and shine brighter\n"
    .string "than anyone can imagine!$"

