# 1 "data/maps/MtMoon_B1F/scripts.pory"

# 2 "data/maps/MtMoon_B1F/scripts.pory"
MtMoon_B1F_MapScripts::
# 3 "data/maps/MtMoon_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/MtMoon_B1F/scripts.pory"

# 5 "data/maps/MtMoon_B1F/scripts.pory"
MtMoon_B1F_EventScript_Sableye::
# 6 "data/maps/MtMoon_B1F/scripts.pory"
	msgbox MtMoon_B1F_Text_Sableye, MSGBOX_NPC
# 7 "data/maps/MtMoon_B1F/scripts.pory"
	end
# 8 "data/maps/MtMoon_B1F/scripts.pory"

# 9 "data/maps/MtMoon_B1F/scripts.pory"
MtMoon_B1F_Text_Sableye::
# 10 "data/maps/MtMoon_B1F/scripts.pory"
	.string "I sense Sableye in these rocks.\n"
# 11 "data/maps/MtMoon_B1F/scripts.pory"
	.string "I can't sense why it's in these\l"
# 12 "data/maps/MtMoon_B1F/scripts.pory"
	.string "rocks now?$"
