PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I am LORELEI of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your POKéMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
	.string "Back again? Impressive!\p"
	.string "Welcome back to the\n"
	.string "POKéMON LEAGUE!\p"
	.string "Thank you for beating those\n"
	.string "villains anywhere they go!\p"
	.string "But let's cut to the chase.\p"
	.string "Your past win means nothing now!\p"
	.string "Let's see if you've grown!\p"
	.string "Prepare for a chilling battle!\p"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "You're better than I thought.\n"
    .string "Go on ahead.\p"
    .string "You only got a taste of the\n"
    .string "POKéMON LEAGUE's power.$"

PokemonLeague_LoreleisRoom_Text_Defeat2::
    .string "Defeated again?!$"  

PokemonLeague_LoreleisRoom_Text_PostBattle2::
    .string "Truly a worthy CHAMPION!\p"  
    .string "Well done!\p"  
    .string "But remember, the challenge\n"  
    .string "never ends!\p"  
    .string "Keep pushing your limits!$" 
