FuchsiaCity_House2_Text_HaveMonForSavingUs::
    .string "I'm the FISHING\n"  
    .string "GURU's brother!\p"  
    .string "I simply Looove fishing!\p"  
    .string "Do you like to fish?$"  

FuchsiaCity_House2_Text_HaveMonForSavingUs2::
    .string "Grand! I like your style!\p"  
    .string "I don't have a spare rod to\n"  
    .string "give you,\l"  
    .string "but I did fish myself up one\l"  
    .string "of these in the SEAFOAM\l"  
    .string "ISLANDS!$"  

FuchsiaCity_House2_Text_ObtainedKabutoFromEmployee::
    .string "{PLAYER} obtained the KABUTO from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ObtainedOmanyteFromEmployee::
    .string "{PLAYER} obtained the OMANYTE from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ExplainFossil::
    .string "I think this POKEMON may be!\n"
    .string "A rare Find!\p"
    .string "Although I'm not too knowledgeable\n"
    .string "On this Stuff!$"

FuchsiaCity_House2_RocketBossWentToBoardroom::
    .string "Hello there, {PLAYER}!\n"  
    .string "How are the fish biting?$"  

