FuchsiaCity_House2_Text_HaveMonForSavingUs::
    .string "I'm the FISHING GURU's youngest\n"
    .string "brother.\p"
    .string "I simply looove fishing!\p"  
    .string "Do you like to fish?$"  

FuchsiaCity_House2_Text_HaveMonForSavingUs2::
    .string "Grand! I like your style!\p"  
    .string "I don't have a spare rod to give\n"  
    .string "you, but I did fish myself up one\l"  
    .string "of these in the SEAFOAM ISLANDS!$"  

FuchsiaCity_House2_Text_ObtainedKabutoFromEmployee::
    .string "{PLAYER} obtained the KABUTO from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ObtainedOmanyteFromEmployee::
    .string "{PLAYER} obtained the OMANYTE from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ExplainFossil::
    .string "I hear this POKéMON's pretty rare!\p"
    .string "Not that I'd know much about that\n"
    .string "sort of stuff…$"

FuchsiaCity_House2_RocketBossWentToBoardroom::
    .string "Hello there, {PLAYER}!\n"  
    .string "How are the fish biting?$"  

