FuchsiaCity_House2_Text_HaveMonForSavingUs::
    .string "I have Fossil you don't\n"
    .string "have for you!$"

FuchsiaCity_House2_Text_ObtainedKabutoFromEmployee::
    .string "{PLAYER} obtained the KABUTO from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ObtainedOmanyteFromEmployee::
    .string "{PLAYER} obtained the OMANYTE from\n"
    .string "the FISHERMAN!$"

FuchsiaCity_House2_Text_ExplainFossil::
    .string "PLACEHOLDER!$"

FuchsiaCity_House2_RocketBossWentToBoardroom::
    .string "PLACEHOLDER!$"

