# 1 "data/maps/Route21_North/scripts.pory"

# 2 "data/maps/Route21_North/scripts.pory"
Route21_North_MapScripts::
# 3 "data/maps/Route21_North/scripts.pory"
	.byte 0
# 4 "data/maps/Route21_North/scripts.pory"

# 5 "data/maps/Route21_North/scripts.pory"
Route21_North_EventScript_Clamperl::
# 6 "data/maps/Route21_North/scripts.pory"
	msgbox Route21_North_Text_Clamperl, MSGBOX_NPC
# 7 "data/maps/Route21_North/scripts.pory"
	end
# 8 "data/maps/Route21_North/scripts.pory"

# 9 "data/maps/Route21_North/scripts.pory"
Route21_North_Text_Clamperl::
# 10 "data/maps/Route21_North/scripts.pory"
	.string "I'm rarely fishing up\n"
# 11 "data/maps/Route21_North/scripts.pory"
	.string "CLAMPERLS now for some reason...\l"
# 12 "data/maps/Route21_North/scripts.pory"
	.string "Guess they got here!$"
