OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Haaaaaaaaaaah!\p"
    .string "Aaaah! This is heavenly!\n"
    .string "The water warms me to my core!\p"
    .string "You should jump in, too.\p"
    .string "Go to the middle, relax, and get\n"
    .string "good and warm!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "My favorite part of bathing comes\n"
    .string "up right after this.\p"
    .string "I enjoy a bowl of chowder to\n"
    .string "warm me from the inside, too!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "The water is perfectly warm.\n"
    .string "It feels exquisite…\p"
    .string "{PLAYER} and the POKéMON were\n"
    .string "fully refreshed!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "Soaking in a hot spring pool is\n"
    .string "therapeutic, people say.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Have a look at my face.\n"
    .string "See how smooth my skin is?\p"
    .string "The hot spring's water keeps my\n"
    .string "skin younger than my age.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "After an honest day of training,\n"
    .string "nothing beats a relaxing soak in\l"
    .string "the hot spring pool.\p"
    .string "BRUNO, who's a senior ahead of me,\n"
    .string "visits the SPA on occasion.\p"
    .string "He comes to rehab injuries, both\n"
    .string "his own and his POKéMON's.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Hot springs go hand-in-hand with\n"
    .string "volcanoes.\p"
    .string "The EMBER SPA here, well,\n"
    .string "I made it years ago.\p"
    .string "I hewed the pool right out of a\n"
    .string "gigantic boulder by hand.\p"
    .string "And while I was working on it,\n"
    .string "I found this thing.\p"
    .string "Here, you can have it!$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "I've been told that it can evolve\n"
    .string "TYROUGE into HITMONTOP.\p"
    .string "I was keeping it as a memento,\n"
    .string "but you'll get more use out of it!$"

OneIsland_KindleRoad_EmberSpa_Text_Samal::  
    .string "Hello there!\p"  
    .string "I'm the legendary SLUGMA\n"  
    .string "CHAMPION!\p"  
    .string "It's the prized POKéMON\n"
    .string "of MT EMBER.\p"
    .string "You may be a regular CHAMPION,\n"  
    .string "but are you a match for a\l"  
    .string "SLUGMA CHAMPION?\p"  
    .string "Well then, let's battle!$"  

OneIsland_KindleRoad_EmberSpa_Text_SamalDefeat::  
    .string "Gosh darn!\p"  
    .string "You are the true SLUGMA CHAMPION!$"  

OneIsland_KindleRoad_EmberSpa_Text_SamalPostBattle::  
    .string "Incredible! I guess that makes\n"  
    .string "you the SLUGMA CHAMPION.\p"  
    .string "I'll keep training!$"  

OneIsland_KindleRoad_EmberSpa_Text_NoSamal::  
    .string "Not SLUGMA enough?$"  

OneIsland_KindleRoad_EmberSpa_Text_YesSamal::  
    .string "Let's get fired up!\p"  
    .string "See who's the strongest!$"  

OneIsland_KindleRoad_EmberSpa_Text_RematchSamal::  
    .string "I've only become more SLUGMA\n"  
    .string "since our last battle!\p"  
    .string "Ready for the rematch\n"  
    .string "of a lifetime?$"  

OneIsland_KindleRoad_EmberSpa_Text_RematchSamalDefeat::  
    .string "Seems SLUGMA CHAMPION-level\n"
    .string "to me!$"  

OneIsland_KindleRoad_EmberSpa_Text_YesRematchSamal::  
    .string "Gosh darn!\p"  
    .string "You are the true SLUGMA CHAMPION!$"  

OneIsland_KindleRoad_EmberSpa_Text_RematchSamalPostBattle::  
    .string "Incredible! I guess that makes\n"  
    .string "you the SLUGMA CHAMPION.\p"  
    .string "I'll keep training!$"  
