Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

Route6_NorthEntrance_Text_FightGuard::
    .string "This road is closed!\n"
    .string "You'd better turn back.\p"
    .string "Unless you're looking to battle?$"

Route6_NorthEntrance_Text_NoFightGuard::
    .string "Good. Now scram!$"

Route6_NorthEntrance_Text_RematchYesSurge::
    .string "Alright then!$"

Route6_NorthEntrance_Text_RematchSurgeDefeat::
    .string "I thought you'd be weaker!$"

Route6_NorthEntrance_Text_PostGuard::
    .string "Alright… Sorry about that.\p"
    .string "I admit that I get a little\n"
    .string "cranky when I'm thirsty.\p"
    .string "You don't look like you'll cause\n"
    .string "much trouble, so I'll tell the\l"
    .string "others to let you through, OK?$"
