Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

Route6_NorthEntrance_Text_FightGuard::
    .string "I said the road is closed\n"
    .string "Please stop comming.\p"
    .string "But actually,\n"
    .string "If you keep comming,\n"
    .string "I might of well just fight you!\p"
    .string "If you want to enter.$"


Route6_NorthEntrance_Text_NoFightGuard::
    .string "Good$"

Route6_NorthEntrance_Text_RematchYesSurge::
    .string "This isn't YOUR ROAD!$"

Route6_NorthEntrance_Text_RematchSurgeDefeat::
    .string "I thought you were weaker!$"

Route6_NorthEntrance_Text_PostGuard::
    .string "Alright Sorry.\p"
    .string "I admit I was just,\n"
    .string "Very Thirsty, and I should of\n"
    .string "Let you guys in.\p"
    .string "I'll tell the others to open.$"
