Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "Grumble, grumble…\n"
    .string "I'm parched… Need a drink…\p"
    .string "Huh? Hey, kid! Can't you see the\n"
    .string "road's closed? Get out of here!$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Grumble, grumble… Huh?\n"
    .string "Is that TEA you've got there?\l"
    .string "It looks awfully tasty…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Finally, I can quench my thirst!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hey, kid, how's it going?$"

Route6_NorthEntrance_Text_FightGuard::
    .string "Grumble, grumble…\n"
    .string "I'm so darn thirsty…\p"
    .string "Hey, kid! The road's closed!\n"
    .string "You'd better turn back, unless\l"
    .string "you're looking for a battle!$"

Route6_NorthEntrance_Text_NoFightGuard::
    .string "Good. Now scram!$"

Route6_NorthEntrance_Text_RematchYesSurge::
    .string "Alright, then!$"

Route6_NorthEntrance_Text_RematchSurgeDefeat::
    .string "I thought you'd be weaker!$"

Route6_NorthEntrance_Text_PostGuard::
    .string "Alright… Sorry about that.\p"
    .string "I admit that I get a little\n"
    .string "cranky when I'm thirsty.\p"
    .string "You don't look like you'll cause\n"
    .string "much trouble, so I'll tell the\l"
    .string "others to let you through, OK?$"
