OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Lying back, rocked by the waves…\n"
    .string "It's exquisite.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "I lost…\n"
    .string "It feels awful.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "The sea is pleasantly warm in these\n"
    .string "parts.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Good things get washed up by the\n"
    .string "ocean current onto this beach.\p"
    .string "That's why I often come here for\n"
    .string "some beachcombing.$"

OneIsland_TreasureBeach_Text_Jasmine::  
    .string "Oh, you're the new\n"  
    .string "KANTO CHAMPION, aren't you?\p"  
    .string "I'm just looking for\n"  
    .string "treasure on this beach.\p"  
    .string "I am JASMINE, LEADER of the\n"  
    .string "OLIVINE CITY GYM in JOHTO!\p"  
    .string "I specialize in STEEL-type\n"  
    .string "POKéMON!\p"  
    .string "I'd love to train with you!$"  

OneIsland_TreasureBeach_Text_JasmineDefeat::  
    .string "Wow, I was stumped!$"  

OneIsland_TreasureBeach_Text_JasminePostBattle::  
    .string "Ah, I see why you're the CHAMPION.\p"  
    .string "You're talented indeed!\p"  
    .string "Continue to treat POKéMON\n"  
    .string "with love and care!$"  

OneIsland_TreasureBeach_Text_NoJasmine::  
    .string "Maybe some other time.$"  

OneIsland_TreasureBeach_Text_YesJasmine::  
    .string "OK, I'm ready!$"  

OneIsland_TreasureBeach_Text_RematchJasmine::  
    .string "You want a rematch?$"  

OneIsland_TreasureBeach_Text_RematchJasmineDefeat::  
    .string "Wow, I was stumped!$"  

OneIsland_TreasureBeach_Text_YesRematchJasmine::  
    .string "OK, I'm ready!$"  

OneIsland_TreasureBeach_Text_RematchJasminePostBattle::  
    .string "Ah, I see why you're the CHAMPION.\p"  
    .string "You're talented indeed!\p"  
    .string "Continue to treat POKéMON\n"  
    .string "with love and care!$"  
