OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Lying back, rocked by the waves…\n"
    .string "It's exquisite.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "I lost…\n"
    .string "It feels awful.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "The sea is pleasantly warm in these\n"
    .string "parts.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Good things get washed up by the\n"
    .string "ocean current onto this beach.\p"
    .string "That's why I often come here for\n"
    .string "some beachcombing.$"

OneIsland_TreasureBeach_Text_Jasmine::  
    .string "Oh, I think you're the\n"  
    .string "KANTO CHAMPION now, huh?\p"  
    .string "I'm just enjoying finding\n"  
    .string "treasure around this beach.\p"  
    .string "I am JASMINE, the OLIVINE\n"  
    .string "CITY GYM LEADER!\p"  
    .string "I specialize in STEEL-type\n"  
    .string "POKéMON!\p"  
    .string "And I could go for a battle\n"  
    .string "right now!$"  

OneIsland_TreasureBeach_Text_JasmineDefeat::  
    .string "Wow, I was stumped!$"  

OneIsland_TreasureBeach_Text_JasminePostBattle::  
    .string "Ah, I see why you are CHAMPION.\p"  
    .string "Talented indeed!\p"  
    .string "Continue to treat POKéMON well\n"  
    .string "with care!$"  

OneIsland_TreasureBeach_Text_NoJasmine::  
    .string "Maybe some other time.$"  

OneIsland_TreasureBeach_Text_YesJasmine::  
    .string "Sounds like it!$"  

OneIsland_TreasureBeach_Text_RematchJasmine::  
    .string "You want a rematch?$"  

OneIsland_TreasureBeach_Text_RematchJasmineDefeat::  
    .string "Wow, I was stumped!$"  

OneIsland_TreasureBeach_Text_YesRematchJasmine::  
    .string "Sounds like it!$"  

OneIsland_TreasureBeach_Text_RematchJasminePostBattle::  
    .string "Ah, I see why you are CHAMPION.\p"  
    .string "Talented indeed!\p"  
    .string "Continue to treat POKéMON well\n"  
    .string "with care!$"  
