PokemonMansion_Text_PressSecretSwitch::
    .string "A secret switch!\p"
    .string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"

PokemonMansion_1F_Text_Oak::
    .string "You've caught me in a moment\n"  
    .string "of deep research.\p"  
    .string "This mansion holds secrets\n"  
    .string "of a Pokémon barely more\l"  
    .string "than a whisper in ancient texts.$"  

PokemonMansion_1F_Text_Oak2::
    .string "Looking at the story of\n"  
    .string "MEWTWO,\l"  
    .string "one ponders its origins..\p"  
    .string "I spent many years exploring\n"  
    .string "the region to discover every\l"  
    .string "species.$" 

PokemonMansion_1F_Text_Oak3::
    .string "There were a few, however.\p" 
    .string "They were so powerful,\n"  
    .string "so rare,\l"  
    .string "I had to keep their capture\l"  
    .string "hidden.$"   

PokemonMansion_1F_Text_Oak4::
    .string "But let's focus on the present.\p"  
    .string "{PLAYER}!\p"  
    .string "You have become a Pokémon\n"  
    .string "master above all others.\p"  
    .string "Our battle has showed me\n"  
    .string "back to the path of strength.\p"  
    .string "Now, I challenge you with my\n"  
    .string "full,\l"  
    .string "unrestrained power.\p"  
    .string "Might I test your might\n"  
    .string "once more?$"

PokemonMansion_1F_Text_OakDefeat::
    .string "This defeat teaches me more\n"  
    .string "than any victory.$"

PokemonMansion_1F_Text_OakPostBattle::
    .string "Our clash today stirred the\n"  
    .string "very air itself.\p"  
    .string "There's a certain energy in\n"  
    .string "this place, ripe with\l"  
    .string "possibility.\p"  
    .string "Keep your senses sharp.\n"  
    .string "The world is full of wonders\l"  
    .string "waiting to reveal themselves\l"  
    .string "to the worthy.\p"  
    .string "Who knows what mysteries\n"  
    .string "may unfold next?$"  

PokemonMansion_1F_Text_NoOak::
    .string "Perhaps it's best to wait\n"  
    .string "until the time feels right.$"  

PokemonMansion_1F_Text_YesOak::
    .string "May our battle echo through\n"  
    .string "these halls.\p"  
    .string "Prepare yourself!$" 

PokemonMansion_1F_Text_Mew::
    .string "Mew.....$" 


