SevenIsland_House_Room2_Text_Evangelos:
	.string "SPEED's the name of the game!\n"
	.string "Can you keep up with my POKéMON?\p"
	.string "Let's zip through some training.$"

SevenIsland_House_Room2_Text_EvangelosPostBattle:
	.string "Zipping right past me! Your\n"
	.string "training's really paying off!$"

SevenIsland_House_Room2_Text_Evvi:
	.string "Brains over brawn… that's how\n"
	.string "I train my POKéMON.\p"
	.string "Let's see if your POKéMON can\n"
	.string "match their power!$"

SevenIsland_House_Room2_Text_EvviPostBattle:
	.string "Such a sharp mind! Your POKéMON\n"
	.string "are getting smarter by the second!$"

SevenIsland_House_Room2_Text_Eva:
	.string "Hey, my POKéMON might not be strong,\n"
	.string "but they sure can endure anything!\p"
	.string "Why not train with me to build\n"
	.string "your POKéMON's endurance?$"

SevenIsland_House_Room2_Text_EvaPostBattle:
	.string "Wow! Your POKéMON sure have\n"
	.string "a lot of stamina! Great job!$"

SevenIsland_House_Room2_Text_Evin:
	.string "My POKéMON love to strike fast\n"
	.string "and hit hard! Care to spar?\p"
	.string "Training with me might boost\n"
	.string "your POKéMON's power!$"

SevenIsland_House_Room2_Text_EvinPostBattle:
	.string "What power! You're really packing\n"
	.string "a punch! Keep it up!$"

SevenIsland_House_Room2_Text_Evern:
	.string "SPECIAL DEFENSES are my specialty.\n"
	.string "Want to build some resilience?\p"
	.string "My Pokémon will teach you to\n"
	.string "weather any storm!$"

SevenIsland_House_Room2_Text_EvernPostBattle:
	.string "Resilient and steady! Your team\n"
	.string "is tough as nails!$"

SevenIsland_House_Room2_Text_Eve:
	.string "DEFENSE is the best offense,\n"
	.string "or so they say!\p"
	.string "Let's toughen up together,\n"
	.string "block by block.$"

SevenIsland_House_Room2_Text_EvePostBattle:
	.string "You're as solid as a rock! That\n"
	.string "was some great training!$"

SevenIsland_House_Room2_Text_BaldMan:
    .string "This place the old woman opened\n"  
    .string "up is great for training a\l"  
    .string "certain Pokémon's stat.$"  
    .string "After Brawling with the black\n"  
    .string "belt, my Pokémon can even\l"  
    .string "strike mountains with great\l"  
    .string "strength!$"  

