Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

Text_DreamEaterReteach::
    .string "Even after teaching you DREAM\n"
    .string "EATER, I still can't forget how to\l"
    .string "eat dreams!\p"
    .string "I'll keep teaching your POKéMON\n"
    .string "DREAM EATER for ¥5000.$"
Text_DreamEaterReteach2::
    .string "Do you want me to teach\n"
    .string "a POKéMON DREAM EATER?$"
Text_DreamEaterNotEnoughMoney::
    .string "The only thing spookier than\n"
    .string "DREAM EATER is not having the\l"
    .string "¥5000 to learn it!\p"
    .string "I'll be happy to teach it to a\n"
    .string "POKéMON when you have enough money.$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "They appeared after MOON STONES\n"
    .string "fell on MT. MOON.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "This is it, the MUSEUM.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "You're a TRAINER, right?\p"
    .string "BROCK's looking for new\n"
    .string "challengers. Follow me!$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff,\n"
    .string "go take on BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
 	.string "Any POKéMON that appears even once\n"
	.string "in a battle is awarded\n"
    .string "EXP Points and EVs.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PEWTER POLICE if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. OAK's AIDE.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "EXP. SHARE from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} put the EXP. SHARE\n"
    .string "in the BAG.$"

PewterCity_Text_ExplainRunningShoes::
    .string "When held by a weaker POKéMON,\n"
    .string "it will recieve experience\p"
    .string "as though it were in battle.$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the LAB.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is an EXP. SHARE for\n"
    .string "my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

PewterCity_Text_AbilityGirl::
	.string "ABILITIES are so cool!\p"
 	.string "POKéMON with PICKUP can find all\n"
 	.string "sorts of items, even RARE CANDY.\p"
 	.string "MAGMA ARMOR is so hot, it evaporates\n"
 	.string "WATER attacks and reduces their\l"
 	.string "damage!\p"
 	.string "STENCH smells so bad that the\n"
 	.string "opponent might miss you, while\l"
 	.string "ILLUMINATE makes it easier to see\l"
 	.string "and ignores accuracy loss!$"
