TwoIsland_CapeBrink_Text_Clair::  
    .string "I've heard of you from\n"  
    .string "LANCE, CHAMPION!\p"  
    .string "You haven't even battled the\n"  
    .string "ELITE FOUR at their full strength!\p"  
    .string "I would know, because I'm\n"  
    .string "the BLACKTHORN CITY GYM\l"  
    .string "LEADER, CLAIR!\p"  
    .string "Master of DRAGONS!\p"  
    .string "Want to battle?$"  

TwoIsland_CapeBrink_Text_ClairDefeat::  
    .string "WHAT?!$"  

TwoIsland_CapeBrink_Text_ClairPostBattle::  
    .string "I won't accept this!\p"  
    .string "If you were battling for\n"  
    .string "my BADGE, I wouldn't deem\l"  
    .string "you worthy!\p"  
    .string "Come back when you're WORTHY.$"  

TwoIsland_CapeBrink_Text_NoClair::  
    .string "Not strong enough, I see.$"  

TwoIsland_CapeBrink_Text_YesClair::  
    .string "Prepare to lose!$"  

TwoIsland_CapeBrink_Text_RematchClair::  
    .string "You're back?\p"  
    .string "I've only grown stronger,\n"  
    .string "you know!\p"  
    .string "Want to lose?$"  

TwoIsland_CapeBrink_Text_RematchClairDefeat::  
    .string "WHAT?!$"  

TwoIsland_CapeBrink_Text_YesRematchClair::  
    .string "I won't lose this time!$"  

TwoIsland_CapeBrink_Text_RematchClairPostBattle::  
    .string "I won't accept this!\p"  
    .string "If you were battling for\n"  
    .string "my BADGE, I wouldn't deem\l"  
    .string "you worthy!\p"  
    .string "Come back when you're WORTHY.$"  


TwoIsland_CapeBrink_Text_Caseno::
    .string "Hey! I'm just trying\n"
    .string "to enjoy the view!\p"
    .string "Your stupid hat is blocking it!\p"
    .string "Look's like I'll have to battle you!$"

TwoIsland_CapeBrink_Text_CasenoDefeat::
    .string "I guess the hat\n"
    .string "gave you strength!$"

TwoIsland_CapeBrink_Text_CasenoPostBattle::
    .string "Huh, you're the KANTO CHAMPION?\n"
    .string "I knew KANTO was stronger.\p"
    .string "Guess I should have read the news.\p"
    .string "Now, if you beat the other\n"
    .string "five MASTERS, you can fight\l"
    .string "the supreme MASTER on SEVEN.$"

TwoIsland_CapeBrink_Text_NoCaseno::
    .string "Good choice.$"

TwoIsland_CapeBrink_Text_YesCaseno::
    .string "Good luck.\p"
    .string "I'm a MASTER!$"

TwoIsland_CapeBrink_Text_RematchCaseno::
    .string "Why are you back?\n"
    .string "Do you want a rematch!$"

TwoIsland_CapeBrink_Text_RematchCasenoDefeat::
    .string "Seems CHAMPION-level to me!$"

TwoIsland_CapeBrink_Text_YesRematchCaseno::
    .string "Seems like you're stronger\n"
    .string "than I thought!$"

TwoIsland_CapeBrink_Text_RematchCasenoPostBattle::
    .string "Ha! Good match!$"
