TwoIsland_CapeBrink_Text_Clair::
    .string "I've heard of you from\n"
    .string "LANCE Champion!\p"
    .string "You haven't even battle them\n"
    .string "at their full strength!p"
    .string "I would know because I'm\n"
    .string "The Blackthorn City GYM Leader,\l"
    .string "CLAIR, LANCE's Cousin!\p"
    .string "Master of DRAGONS!\p"
    .string "Want to battle?$"


TwoIsland_CapeBrink_Text_ClairDefeat::
    .string "WHAT!$"

TwoIsland_CapeBrink_Text_ClairPostBattle::
    .string "I won't accept this!\p"
    .string "If you were battling\p"
    .string "for my BADGE I wouldn't\n"
    .string "Deem you worthy!\p"
    .string "Come back when you're WORTHY.$"

TwoIsland_CapeBrink_Text_NoClair::
    .string "Not Strong enough I see.$"

TwoIsland_CapeBrink_Text_YesClair::
    .string "Prepare to Lose!$"

TwoIsland_CapeBrink_Text_RematchClair::
    .string "You're Back?\p"
    .string "I've only grew strong\n"
    .string "You know!\p"
    .string "Want to lose?$"

TwoIsland_CapeBrink_Text_RematchClairDefeat::
    .string "WHAT!$"

TwoIsland_CapeBrink_Text_YesRematchClair::
    .string "I won't lose this time!$"

TwoIsland_CapeBrink_Text_RematchClairPostBattle::
    .string "I won't accept this!\p"
    .string "If you were battling\p"
    .string "for my BADGE I wouldn't\n"
    .string "Deem you worthy!\p"
    .string "Come back when you're WORTHY.$"

TwoIsland_CapeBrink_Text_Caseno::
    .string "Hey! I'm just trying\n"
    .string "to enjoy the view!\p"
    .string "Your Stupid Hat is\n"
    .string "Blocking it!\p"
    .string "Look's Like I'll\n"
    .string "have to battle you!$"

TwoIsland_CapeBrink_Text_CasenoDefeat::
    .string "I guess the hat\n"
    .string "Gave you strength$"

TwoIsland_CapeBrink_Text_CasenoPostBattle::
    .string "Huh, you're the KANTO Champion?\n"
    .string "I knew KANTO was stronger.\p"
    .string "Guess I should of read the news.\p"
    .string "Now, If you beat the other\n"
    .string "five Masters, you can fight\l"
    .string "Supreme Master On Seven.$"

TwoIsland_CapeBrink_Text_NoCaseno::
    .string "Good Choice$"

TwoIsland_CapeBrink_Text_YesCaseno::
    .string "Good Luck.\p"
    .string "I'm a Master!$"

TwoIsland_CapeBrink_Text_RematchCaseno::
    .string "Why are you back?\n"
    .string "Do you want a rematch!$"

TwoIsland_CapeBrink_Text_RematchCasenoDefeat::
    .string "Seems Champion Level to me!$"

TwoIsland_CapeBrink_Text_YesRematchCaseno::
    .string "Seems like you're!\n"
    .string "Stronger than I thought!$"

TwoIsland_CapeBrink_Text_RematchCasenoPostBattle::
    .string "Ha! Good Match!$"
