PokemonLeague_ChampionsRoom_Text_Intro::
    .string "{RIVAL}: Hey, {PLAYER}!\p"
    .string "I was looking forward to seeing\n"
    .string "you, {PLAYER}.\p"
    .string "My rival should be strong to keep\n"
    .string "me sharp.\p"
    .string "While working on my POKéDEX, I\n"
    .string "looked all over for POKéMON.\p"
    .string "Not only that, I assembled teams\n"
    .string "that would beat any POKéMON type.\p"
    .string "And now…\p"
    .string "I'm the POKéMON LEAGUE CHAMPION!\p"
    .string "{PLAYER}!\n"
    .string "Do you know what that means?\p"
    .string "I'll tell you.\p"
    .string "I am the most powerful TRAINER in\n"
    .string "the world!$"

PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .string "Back again?\p"  
    .string "I've been waiting, {PLAYER}!\p"  
    .string "This time, my team's stronger\n"  
    .string "and ready to take you down!\p"  
    .string "Ready to hand over that title?\p"  
    .string "Let's do this!\p"  
    .string "No holding back!$"  

PokemonLeague_ChampionsRoom_Text_Defeat::
    .string "NO!\n"
    .string "That can't be!\l"
    .string "You beat me at my best!\p"
    .string "After all that work to become\n"
    .string "the LEAGUE CHAMP?\p"
    .string "My reign is over already?\n"
    .string "It's not fair!$"

PokemonLeague_ChampionsRoom_Text_Defeat2::
    .string "Even with my strongest team,\n"  
    .string "your skills as CHAMPION…\p"  
    .string "They're real.$"  

PokemonLeague_ChampionsRoom_Text_Victory::
    .string "はーはッ！\n"
    .string "かった！　かった！　かった！\p"
    .string "{PLAYER}に　まける　ような\n"
    .string "おれさま　では　なーい！\p"
    .string "ま！　ポケモンの\n"
    .string "てんさい　{RIVAL}さま　あいてに\l"
    .string "ここまで　よく　がんばった！\p"
    .string "ほめて　つかわす！\n"
    .string "はーッ！　はーはッはッ！$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
    .string "Why?\n"
    .string "Why did I lose?\p"
    .string "I never made any mistakes raising\n"
    .string "my POKéMON…\p"
    .string "Darn it! You're the new POKéMON\n"
    .string "LEAGUE CHAMPION!\p"
    .string "Although I don't like to admit it…$"

PokemonLeague_ChampionsRoom_Text_PostBattle2::
    .string "Fine, you win.\n"  
    .string "You're the best, {PLAYER}.\p"  
    .string "But I won't give up just yet!\p"  
    .string "Next time I'll be CHAMPION.$"  

PokemonLeague_ChampionsRoom_Text_OakPlayer::
    .string "OAK: {PLAYER}!$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
    .string "OAK: So, you've won!\n"
    .string "Sincerely, congratulations!\p"
    .string "You're the new POKéMON LEAGUE\n"
    .string "CHAMPION!\p"
    .string "You've grown up so much since you\n"
    .string "first left with {STR_VAR_1} to work\l"
    .string "on the POKéDEX.\p"
    .string "{PLAYER}, you have come of age!$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations2::
    .string "OAK: So, you won again!\p"  
    .string "Congratulations!\n"  
    .string "Still the CHAMP, I see!\p"  
    .string "You've returned,\n"  
    .string "proving your strength once again!\p"  
    .string "Your bond with your POKéMON\n"  
    .string "is truly inspiring!\p"  
    .string "{PLAYER}, you're a true CHAMPION!$"  

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
    .string "OAK: {RIVAL}…\n"
    .string "I'm disappointed in you.\p"
    .string "I came when I heard you'd beaten\n"
    .string "the ELITE FOUR.\p"
    .string "But, when I got here, you had\n"
    .string "already lost!\p"
    .string "{RIVAL}, do you understand why\n"
    .string "you lost?\p"
    .string "You have forgotten to treat your\n"
    .string "POKéMON with love and trust.\p"
    .string "Without them, you will never\n"
    .string "become a CHAMP again!$"

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival2::
    .string "OAK: Ah, {RIVAL}…\p"  
    .string "I had hoped for a better outcome.\p"  
    .string "But I see you have\n"  
    .string "fallen short once more!\p"  
    .string "Remember, {RIVAL},\p"  
    .string "It's not just about\n"  
    .string "strength in battle,\l"  
    .string "but also about the\l"  
	.string "bond you share with your POKéMON.\p"
    .string "Reflect on this, and grow stronger!$"  

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
    .string "OAK: {PLAYER}.\p"
    .string "You understand that your victory\n"
    .string "was not just your own doing.\p"
    .string "The bond you share with your\n"
    .string "POKéMON is marvelous.\p"
    .string "{PLAYER}!\n"
    .string "Come with me!$"

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe2::
    .string "OAK: {PLAYER}!\p"  
    .string "Your triumph is not yours alone!\p"  
    .string "Your bond with your POKéMON\n"  
    .string "is a lesson for us all!\p"  
    .string "{PLAYER},\n"  
    .string "let's celebrate your achievement!$"  
