FiveIsland_LostCave_Room12_Text_Owl::
    .string "...?$"

FiveIsland_LostCave_Room12_Text_OwlDefeat::
    .string "...!$"

FiveIsland_LostCave_Room12_Text_OwlPostBattle::
    .string "...!$"


FiveIsland_LostCave_Room12_Text_NoOwl::
    .string "...$"

FiveIsland_LostCave_Room12_Text_YesOwl::
    .string "...!$"

FiveIsland_LostCave_Room12_Text_RematchOwl::
    .string "...$"


FiveIsland_LostCave_Room12_Text_RematchOwlDefeat::
    .string "...$"

FiveIsland_LostCave_Room12_Text_YesRematchOwl::
    .string "...!$"

FiveIsland_LostCave_Room12_Text_RematchOwlPostBattle::
    .string "...!$"


