SixIsland_AlteringCave_Text_Spike::
    .string "What are you doing in here?!$"

SixIsland_AlteringCave_Text_SpikeDefeat::
    .string "I guess that's strength!$"

SixIsland_AlteringCave_Text_SpikePostBattle::
    .string "Since I lost, I ought to tell.\p"
    .string "This place switches encounters\n"
    .string "quite often.$"

SixIsland_AlteringCave_Text_NoSpike::
    .string "Go away!$"

SixIsland_AlteringCave_Text_YesSpike::
    .string "Oh, I guess you want a fight?$"

SixIsland_AlteringCave_Text_RematchSpike::
    .string "Not again…$"

SixIsland_AlteringCave_Text_RematchSpikeDefeat::
    .string "I guess that's strength!$"

SixIsland_AlteringCave_Text_YesRematchSpike::
    .string "Alright, let's fight!$"

SixIsland_AlteringCave_Text_RematchSpikePostBattle::
    .string "Please go away,\n"
    .string "I don't want to write more text!$"
