SixIsland_AlteringCave_Text_Spike::
    .string "Spike Placeholder!$"

SixIsland_AlteringCave_Text_SpikeDefeat::
    .string "Spike Placeholder!$"

SixIsland_AlteringCave_Text_SpikePostBattle::
    .string "Spike Placeholder!$"

SixIsland_AlteringCave_Text_NoSpike::
    .string "Spike Placeholder!$"

SixIsland_AlteringCave_Text_YesSpike::
    .string "Spike Placeholder!$"

SixIsland_AlteringCave_Text_RematchSpike::
    .string "Spike Rematch Placeholder!$"

SixIsland_AlteringCave_Text_RematchSpikeDefeat::
    .string "Spike Rematch Placeholder!$"

SixIsland_AlteringCave_Text_YesRematchSpike::
    .string "Spike Rematch Placeholder!$"

SixIsland_AlteringCave_Text_RematchSpikePostBattle::
    .string "Spike Rematch Placeholder!$"
