CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Hi!\p"
    .string "Sorry, but we're taking a break\n"
    .string "right now.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "My POKéMON are weak, so I often\n"
    .string "have to go to the DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Psst! There's a basement under the\n"
    .string "GAME CORNER, I hear.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Munch…\p"
    .string "The man at that table lost it all\n"
    .string "at the slots.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Go ahead! Laugh!\n"
    .string "I'm flat-out busted!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I won't be needing this anymore!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Make room for this!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "I always thought I was going to\n"
    .string "win it back…$"

CeladonCity_Restaurant_Text_29Years::
	.string "Alright, kid… I'm 29 years old, and\n"
	.string "I still haven't figured out this\l"
	.string "restaurant stuff…\p"
	.string "I want to have the chicken meatballs\n"
	.string "that I saw advertised on the wall.\p"
	.string "But all they gave me was a MENU!\p"
	.string "I've checked Page 1, Page 2, and\n"
	.string "Page 3…\l"
	.string "Nothing!\p"
	.string "Stop playing with me!\n"
	.string "Put some respect on my name!$"
