CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Hi!\p"
    .string "Sorry, but we're taking a break\n"
    .string "right now.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "My POKéMON are weak, so I often\n"
    .string "have to go to the DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Psst! There's a basement under the\n"
    .string "GAME CORNER, I hear.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Munch…\p"
    .string "The man at that table lost it all\n"
    .string "at the slots.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Go ahead! Laugh!\n"
    .string "I'm flat-out busted!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I won't be needing this anymore!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Make room for this!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "I always thought I was going to\n"
    .string "win it back…$"

CeladonCity_Restaurant_Text_29Years::
	.string "Alright dude, I'm 29 years\n"
	.string "old and still have yet to\l"
	.string "figure out Restaurants.\p"
	.string "I want Chicken Meatballs,\n"
	.string "I saw on the wall.\p"
	.string "All they gave me was a\n"
	.string "MENU!\p"
	.string "I checked Page 1, Page 2,\n"
	.string "and Page 3…\l"
	.string "nothing!\p"
	.string "Stop playing with me!\p"
	.string "Put some respect on\n"
	.string "my name!$"
