SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} found a SAPPHIRE!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu…\n"
    .string "I guessed right.\p"
    .string "I was right in tailing you!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "I knew that there was a SAPPHIRE\n"
    .string "here, so it belongs to me!\p"
    .string "I'll use this to hold control over\n"
    .string "the SEVII Island along with\n"
    .string "TEAM ROCKET!\p"
    .string "Oh... Your the Kanto Champion Huh?\p"
    .string "You Kantonians are really something,\n"
    .string "I hope you like chasing me down!\p"
    .string "I'll even tell you one of the\n"
    .string "passwords to TEAM ROCKET's\l"
    .string "WAREHOUSE.\p"
    .string "The WAREHOUSE password I know is\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "I'm done.\n"
    .string "Don't think badly of me!$"

