FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "I'm the eldest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the beak.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "Oh, so sharp!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "You can fly to FOUR ISLAND from\n"
    .string "here.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "I'm the middle kid of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the wings.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "There was a really somber guy\n"
    .string "over that way, and\l"
    .string "there's also a weird TREE here.\p"
    .string "I wonder if the weird TREE\n"
    .string "reacts to tears?$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "I'm the youngest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the down.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Down is so comfy…\n"
    .string "It makes me drowsy…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "It fills me with happiness when\n"
    .string "bird POKéMON beg playfully…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Scrub, scrub…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Hello…\n"
    .string "Your POKéMON look healthy…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "This is where I buried my ONIX…\n"
    .string "It was named TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.\p"
    .string "There is a LEMONADE placed as an\n"
    .string "offering in front of the grave.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Would you like to leave another\n"
    .string "LEMONADE as an offering?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} placed a can of LEMONADE\n"
    .string "in front of the grave.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "Th-thank you…\p"
    .string "That was my TECTONIX's favorite\n"
    .string "drink…\p"
    .string "I don't even know you, but your\n"
    .string "act of kindness…\p"
    .string "It's uplifted me a little.\p"
    .string "Can you please take this as my\n"
    .string "thanks?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Please be good to your POKéMON,\n"
    .string "too.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "If you don't have room for it,\n"
    .string "I'll hold it for you till next time.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Oh, it's you from that time…\p"
    .string "I still have that thing I wanted\n"
    .string "you to have as my thanks.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Scrub, scrub…\p"
    .string "… … …\n"
    .string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Boulders and rocks are neatly piled\n"
    .string "up as a cairn.\p"
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.$"

FiveIsland_MemorialPillar_Text_Oman::  
    .string "Wow, I can't believe he'd\n"  
    .string "use a POKéMON weak to water\l"  
    .string "on these oceanic islands!\p"  
    .string "Unlucky for him.\p"  
    .string "I've also had to put up with\p"  
    .string "less than stellar POKéMON,\p"  
    .string "but I grew strong despite it.\p"  
    .string "Want to see them?$"  

FiveIsland_MemorialPillar_Text_OmanDefeat::  
    .string "I guess that was expected.$"  

FiveIsland_MemorialPillar_Text_OmanPostBattle::  
    .string "Looks like I've been bested.\p"  
    .string "That's to be expected,\n"
    .string "given my POKéMON.\p"  
    .string "You made better use of them\n"
    .string "than I possibly could've.\p"
    .string "I know I can grow stronger.\n"  
    .string "It's just a matter of time.$"  

FiveIsland_MemorialPillar_Text_NoOman::  
    .string "Maybe some other time.$"  

FiveIsland_MemorialPillar_Text_YesOman::  
    .string "Good luck… to me.\p"  
    .string "Let's battle!$"  

FiveIsland_MemorialPillar_Text_RematchOman::  
    .string "You're back.\n"  
    .string "Well, I've got\l"  
    .string "nothing to do, so let's battle!$"  

FiveIsland_MemorialPillar_Text_RematchOmanDefeat::  
    .string "I guess that was expected.$"  

FiveIsland_MemorialPillar_Text_YesRematchOman::  
    .string "Good luck… to me.\p"  
    .string "Let's battle!$"  

FiveIsland_MemorialPillar_Text_RematchOmanPostBattle::  
    .string "Looks like I've been bested.\p"  
    .string "That's to be expected,\n"
    .string "given my POKéMON.\p"  
    .string "You made better use of them\n"
    .string "than I possibly could've.\p"
    .string "I know I can grow stronger.\n"  
    .string "It's just a matter of time.$"  
