Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"

Route1_Text_Oak::
    .string "OAK: Oh, my!\p"  
    .string "It seems you caught me during\n"  
    .string "my lunch hour!\p"  
    .string "{PLAYER}, you have truly\n"  
    .string "come into your own!\p"  
    .string "Your POKÉMON LEAGUE challenge\n"  
    .string "has reignited a spirit that\l"  
    .string "left me a long time ago...\p"  
    .string "Back in my day, I was a\n"  
    .string "serious TRAINER!\p"  
    .string "How about we spar a bit?\n"  
    .string "What say you?$"

Route1_Text_OakDefeat::
    .string "Hmm...\p"  
    .string "I still have a lot to learn!$" 

Route1_Text_OakPostBattle::
    .string "Well done, {PLAYER}!\p"  
    .string "You've certainly proved your\n"  
    .string "mettle.\p"  
    .string "It seems I might be getting\n"  
    .string "a bit rusty in my old age.\p"  
    .string "A good trainer always strives\n"  
    .string "for improvement, and so shall I.\p"  
    .string "May your journey continue to be\n"  
    .string "one of growth and discovery.$"  
    
Route1_Text_NoOak::
    .string "Maybe some other time!$"  

Route1_Text_YesOak::
    .string "Excellent!\p"  
    .string "Prepare yourself for a\n"  
    .string "real challenge!$"   

 


