Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with\n"
    .string "HM06 ROCK SMASH.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received HM06 ROCK SMASH\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "ROCK SMASH can be used to break\n"
    .string "Smashable Rocks and can even\l"
    .string "Find Encounters!\p"
    .string "You don't need any BADGES\n"
    .string "to use ROCK SMASH!$"

Route10_PokemonCenter_1F_Text_Nurse::
    .string "Oh Hello Champion!\p"
    .string "I am going to heal your pokemon\p"
    .string "But first, I want to know if you\n"
    .string "want a battle with me?$"

Route10_PokemonCenter_1F_Text_NurseDefeat::
    .string "Amazing!$"

Route10_PokemonCenter_1F_Text_NursePostBattle::
    .string "That's what I expect!\p"
    .string "Continue to grow stronger,\n"
    .string "I'll always be here!$"

Route10_PokemonCenter_1F_Text_NoNurse::
    .string "Oh I guess you just want to heal.$"

Route10_PokemonCenter_1F_Text_YesNurse::
    .string "I won't disappoint!\p"
    .string "I am pretty strong!$"

Route10_PokemonCenter_1F_Text_RematchNurse::
    .string "Do you want to have another battle.$"

Route10_PokemonCenter_1F_Text_RematchNurseDefeat::
    .string "Amazing!$"

Route10_PokemonCenter_1F_Text_PostRematchNurse::
    .string "That's what I expect!\p"
    .string "Continue to grow stronger,\n"
    .string "I'll always be here!$"

Route10_PokemonCenter_1F_Text_BattleNurse::
    .string "Wait Hold up!$"
