Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with\n"
    .string "HM06 ROCK SMASH.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received HM06 ROCK SMASH\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "ROCK SMASH can be used to break\n"
    .string "smashable rocks, and you can\l"
    .string "sometimes encounter wild POKéMON\l"
    .string "in the rubble.\p" 
    .string "You'll need LT SURGE's BADGE\n"
    .string "to use ROCK SMASH.$"

Route10_PokemonCenter_1F_Text_Nurse::
	.string "I've always dreamed of\n"  
	.string "becoming a POKéMON MASTER,\p"  
	.string "but my duties here make\n"  
	.string "it hard to travel\l"  
	.string "and collect badges.\p"  
	.string "It would be a great honor\n"  
	.string "to test my skills\p"  
	.string "against the new CHAMPION.\p"  
	.string "Could I ask for a battle?$"  

Route10_PokemonCenter_1F_Text_NurseDefeat::
	.string "That was amazing!$"  

Route10_PokemonCenter_1F_Text_NursePostBattle::
	.string "That was amazing!\p"  
	.string "Your strength and bond\n"  
	.string "with your POKéMON is inspiring.\p"  
	.string "This battle has\n"  
	.string "taught me so much.\p"  
	.string "Thank you for this opportunity!\p"  
	.string "I hope we can battle again\n"  
	.string "sometime!$"  

Route10_PokemonCenter_1F_Text_NoNurse::
	.string "I understand.\n"  
	.string "Duty calls, and so does yours.\p"  
	.string "Maybe another time, then.$"  

Route10_PokemonCenter_1F_Text_YesNurse::
	.string "Thank you!\p"  
	.string "This means a lot to me.\p"  
	.string "Let's give it our best shot!$"  

Route10_PokemonCenter_1F_Text_RematchNurse::
	.string "It would be a great honor\n"  
	.string "to test my skills against\p"  
	.string "the new CHAMPION again!\p"   
    .string "Do you want to have another battle?$"

Route10_PokemonCenter_1F_Text_RematchNurseDefeat::
    .string "Amazing!$"

Route10_PokemonCenter_1F_Text_PostRematchNurse::
    .string "Continue to grow stronger,\n"
    .string "I'll always be here!$"

Route10_PokemonCenter_1F_Text_BattleNurse::
	.string "Actually, before you go…$" 

Route10_PokemonCenter_1F_Text_GiveHM05IfSeen10Mons::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with\n"
    .string "HM05 FLASH for you, and if\l"
	.string "you're looking for the AIDE with\l"  
	.string "ROCK SMASH, he's on ROUTE 2.\p"  
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedHM05FromAide::
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainHM05::
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.$"

Route10_PokemonCenter_1F_Text_CanGetThroughRockTunnel::
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"
