FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "There are many POKéMON locked\n"
    .string "away in the pen…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "The pen door is unlocked.\n"
    .string "The POKéMON appear to have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Did you come here knowing it's\n"
    .string "TEAM ROCKET's WAREHOUSE?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET broke up?\n"
    .string "What planet are you from?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oh, now your POKéMON look strong.\n"
    .string "You're willing to sell them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oh, but…\n"
    .string "Too much!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "We can give you a great price.\n"
    .string "Sell us your POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "I got word about you from the\n"
    .string "others.\p"
    .string "But there's no way a kid like you'd\n"
    .string "know our BOSS GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Don't…you…dare…laugh…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Don't mess in the doings of adults,\n"
    .string "you jumped-up pip-squeak!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "I don't know or care if what I'm\n"
    .string "doing is right or wrong…\p"
    .string "I just put my faith in GIOVANNI\n"
    .string "and do as I am told.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "I…\n"
    .string "I'm shattered…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "You're doing things according to\n"
    .string "your beliefs and morals.\p"
    .string "I understand now…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go get rested and\n"
    .string "refreshed for what lies ahead?\p"
    .string "The ADMIN after me outranks me\n"
    .string "thoroughly as a TRAINER.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh challenge.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "That's quite enough of you \n"
    .string "playing the hero, kid.\p"
    .string "Spreading lies about how TEAM\n"
    .string "ROCKET has disbanded…\p"
    .string "It's such an obvious attempt to\n"
    .string "cause confusion in our ranks.\p"
    .string "Fortunately, we're not so ignorant\n"
    .string "to fall for the lies of a child!\p"
    .string "And now, I'll show you how scary\n"
    .string "an angry adult can be!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "You were too strong…\p"
    .string "…\n"
    .string "Th-that's GIOVANNI's BADGE!\p"
    .string "So it's true?\n"
    .string "TEAM ROCKET really has disbanded?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "We will abandon this WAREHOUSE…\p"
    .string "But don't think this is over.\n"
    .string "I won't let this be the end.\p"
    .string "I will find GIOVANNI.\n"
    .string "And I will resurrect TEAM ROCKET!\l"
    .string "I will…\p"
    .string "Until then, farewell!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "A report with graphs and text is on\n"
    .string "the PC monitor.\p"
    .string "“The Influence of Magnetic Waves\n"
    .string "on POKéMON Evolution”…\p"
    .string "… … … … … …\p"
    .string "It's too difficult to understand…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Hmm so it seems like you made it\n"
    .string "though the admins, who left…\p"
    .string "I'll tell you, I was just using them\n"
    .string "to futher my goals.\p"
    .string "Fufu… Fufufufu…\n"
    .string "I am stronger than them of course...\p"
    .string "I always knew their boss went AWOL,\n"
    .string "I consider them quite dumb\l"
    .string "thinking I was just a pawn.\p"
    .string "My entire plan was to control the.\n"
    .string "SAPPHIRE to hold the\l"
    .string "solution to the power,\l"
    .string "needed to Power the SEVII Islands.\p"
    .string "For all this time I was abused and\n"
    .string "controlled By Kantonians, \l"
    .string "I will finally show\l"
    .string "mine and this Islands True power!\p"
    .string "Prepare to lose Kantonian!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Sigh, I guess this is my fault\p"
    .string "I tried to do evil deeds\n"
    .string "In order to fix this region\p"
    .string "I didn't anyone else to give find\n"
    .string "the SAPPHIRE and leave this region\l"
    .string "in the Dust while Kanto Flourish's\p"
    .string "But I should of come to my senses,\n"
    .string "that working with Team Rocket was\l"
    .string "probably not the best way to do it.\p"
    .string "I have seen the good heart you have\n"
    .string "and how you have been trying to help\l"
    .string "this region with the SAPPHIRE\p"
    .string "So, I leave you with this$"


FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "I think now I should transform\n"
    .string "This warehouse for the Islands.\p"
    .string "Leaving it's Rocket Origins for a\n"
    .string "New Purpose.\p"
    .string "Shall you use the SAPPHIRE for Good!$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "What, you again?\p"
    .string "You seem to be GIOVANNI's,\n"
    .string "Kid, aren't you?\p"
    .string "No, that can't be right!\n"
    .string "GIOVANNI's kid has red hair.\p"
    .string "Oh uh anyways I'm doing good\n"
    .string "on reconstructing this place!\p"
    .string "There should be some people to\n"
    .string "talk to with interest things to do$"

FiveIsland_RocketWarehouse_Text_Clerk::
	.string "Hey, you defeated the\n"
	.string "JOHTO LEADERS!\p"
	.string "You deserve to get\n"
	.string "access to my list\l"
	.string "of goods!$"
