FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "There are many POKéMON locked\n"
    .string "away in the pen…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "The pen door is unlocked.\n"
    .string "The POKéMON appear to have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Did you come here knowing it's\n"
    .string "TEAM ROCKET's WAREHOUSE?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET broke up?\n"
    .string "What planet are you from?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oh, now your POKéMON look strong.\n"
    .string "You're willing to sell them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oh, but…\n"
    .string "Too much!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "We can give you a great price.\n"
    .string "Sell us your POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "I got word about you from the\n"
    .string "others.\p"
    .string "But there's no way a kid like you'd\n"
    .string "know our BOSS GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Don't…you…dare…laugh…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Don't mess in the doings of adults,\n"
    .string "you jumped-up pip-squeak!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "I don't know or care if what I'm\n"
    .string "doing is right or wrong…\p"
    .string "I just put my faith in GIOVANNI\n"
    .string "and do as I am told.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "I…\n"
    .string "I'm shattered…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "You're doing things according to\n"
    .string "your beliefs and morals.\p"
    .string "I understand now…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go get rested and\n"
    .string "refreshed for what lies ahead?\p"
    .string "The ADMIN after me outranks me\n"
    .string "thoroughly as a TRAINER.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh challenge.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "That's quite enough of you \n"
    .string "playing the hero, kid.\p"
    .string "Spreading lies about how TEAM\n"
    .string "ROCKET has disbanded…\p"
    .string "It's such an obvious attempt to\n"
    .string "cause confusion in our ranks.\p"
    .string "Fortunately, we're not so ignorant\n"
    .string "to fall for the lies of a child!\p"
    .string "And now, I'll show you how scary\n"
    .string "an angry adult can be!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh…\n"
    .string "You were too strong…\p"
    .string "…\n"
    .string "Th-that's GIOVANNI's BADGE!\p"
    .string "So it's true?\n"
    .string "TEAM ROCKET really has disbanded?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "We will abandon this WAREHOUSE…\p"
    .string "But don't think this is over.\n"
    .string "I won't let this be the end.\p"
    .string "I will find GIOVANNI.\n"
    .string "And I will resurrect TEAM ROCKET!\l"
    .string "I will…\p"
    .string "Until then, farewell!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "A report with graphs and text is on\n"
    .string "the PC monitor.\p"
    .string "“The Influence of Magnetic Waves\n"
    .string "on POKéMON Evolution”…\p"
    .string "… … … … … …\p"
    .string "It's too difficult to understand…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "So you got through the ADMINS…\n"
    .string "What a bunch of disorganised dullards!\p"
    .string "I'll tell you, I've only been using\n"
    .string "them to futher my own goals!\p"
    .string "Fufu… Fufufufu…\p"
    .string "Once I heard that the boss went AWOL,\n"
    .string "I decided I'd snatch the SAPPHIRE\l"
    .string "from under their noses.\p"
    .string "No more will SEVII linger in the\n"
    .string "shadow of KANTO…\p"
    .string "Prepare to lose!$"
    
FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Sigh… I guess this is my fault.\p"
    .string "KANTO gets all the infrastructure\n"
    .string "and technology, while it seems the\l"
    .string "SEVII ISLANDS are always left behind.\p"
    .string "I'd heard that people from KANTO\n"
    .string "were looking for the SAPPHIRE.\p"
    .string "I was hoping I could use it to do\n"
    .string "something for the islands for once.\p"
    .string "But I suppose aligning myself with\n"
    .string "TEAM ROCKET wasn't the best way\l"
    .string "to go about it…\p"
    .string "Wait? Huh? You're giving this to\n"  
    .string "someone who's building a machine\l"  
    .string "that will help the islands?\p"  
    .string "I suppose I was wrong about you!\p"  
    .string "Here, you can take it!$" 

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Don't think bad about me now!\n"  
    .string "I suppose I'll help clean up\l"  
    .string "this place…$"  

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Oh, it's you again.\p"
    .string "Wait… You're not GIOVANNI's\n"
    .string "kid, are you?\p"
    .string "No, that can't be right!\n"
    .string "GIOVANNI's kid has red hair.\p"
    .string "I'm currently being\n"  
    .string "investigated for my involvement\l"  
    .string "with TEAM ROCKET.\p"  
    .string "I'm hoping that, with good \n"  
    .string "behavior, they'll just give me\l"  
    .string "community service…$"


FiveIsland_RocketWarehouse_Text_Clerk::
    .string "That officer and I are the\n"  
    .string "only ones on the SEVII ISLANDS.\p"  
    .string "Not many people live here,\n"  
    .string "so we don’t need a big\l"  
    .string "police force.\p"  
    .string "But we can always contact\n"  
    .string "KANTO officers to aid us\l"  
    .string "whenever we need.$"  


