@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} entered a password.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "Another password is needed to\n"
    .string "open the door…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} entered two passwords.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "The WAREHOUSE's door opened!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "The WAREHOUSE's door is already\n"
    .string "open.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "You don't have any business here!\n"
    .string "Go home!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "There's nothing past here except\n"
    .string "our WAREHOUSE.\p"
    .string "So what brings you here?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "That wasn't supposed to happen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "You're wanting to know what's inside\n"
    .string "this WAREHOUSE?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"

FiveIsland_Meadow_Text_Beasts::
	.string "Hey! I'm just playing\n"
	.string "in this meadow.\p"
	.string "What do you want?\p"
	.string "I actually found something\n"
	.string "interesting somewhere…\p"
	.string "But I'll only give it to\n"
	.string "someone worthy.\p"
	.string "Someone who can catch all\n"
	.string "three of the legendary\l"
	.string "beasts: ENTEI, SUICUNE,\l"
	.string "and RAIKOU.\p"
    .string "Here's what they\n"  
    .string "look like!$"  

FiveIsland_Meadow_Text_Beasts22::
	.string "I heard one of them roams\n"
	.string "KANTO at a single time\l"
	.string "following a Great achievement, \l"
	.string "as long as you caught one of them.\p"
	.string "If you can, I'll give you\n"
	.string "the item!$"

FiveIsland_Meadow_Text_Beasts2::
	.string "Wait, you actually did?\p"
	.string "Well, I guess I'll have\n"
	.string "to give you this then!$"

FiveIsland_Meadow_Text_Beasts3::
	.string "I actually found this when I\n"
	.string "was just wandering about.\p"
	.string "However, I know how\n"
	.string "valuable and sacred\l"
	.string "that island is!\p"
	.string "So I only trust it to\n"
	.string "someone who will treat\l"
	.string "POKéMON well.\p"
	.string "And I can see that\n"
	.string "in you!$"

FiveIsland_Meadow_Text_MayIHelpYou::
	.string "Hey! You defeated the\n"
	.string "SEVII MASTERS!\p"
	.string "You deserve to get\n"
	.string "access to my list\l"
	.string "of goods!$"

