Route13_Text_SebastianIntro::
    .string "My bird POKéMON want to battle\n"
    .string "with you!$"

Route13_Text_SebastianDefeat::
    .string "My PIDGEY and PIDGEOTTO combo\n"
    .string "lost?$"

Route13_Text_SebastianPostBattle::
    .string "My POKéMON look happy even though\n"
    .string "they lost.$"

Route13_Text_SusieIntro::
    .string "I'm told I'm good for a kid.$"

Route13_Text_SusieDefeat::
    .string "Ohh!\n"
    .string "I lost!$"

Route13_Text_SusiePostBattle::
    .string "I want to become a good TRAINER.\n"
    .string "I'll train hard, just watch.$"

Route13_Text_ValerieIntro::
    .string "Wow!\n"
    .string "Your BADGES are too cool!$"

Route13_Text_ValerieDefeat::
    .string "Not enough!$"

Route13_Text_ValeriePostBattle::
    .string "You got those BADGES from GYM\n"
    .string "LEADERS. I know!$"

Route13_Text_GwenIntro::
    .string "My cute POKéMON wish to make your\n"
    .string "acquaintance.$"

Route13_Text_GwenDefeat::
    .string "Good going!\n"
    .string "You totally won!$"

Route13_Text_GwenPostBattle::
    .string "You have to make POKéMON battle\n"
    .string "to toughen them up.$"

Route13_Text_AlmaIntro::
    .string "I found CARBOS in a cave once\n"
    .string "while I was spelunking.$"

Route13_Text_AlmaDefeat::
    .string "Oh, too bad!\n"
    .string "I just messed up!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS boosted the SPEED of my\n"
    .string "POKéMON.$"

Route13_Text_PerryIntro::
    .string "I'm not going to lose.\n"
    .string "Not when the wind's blowing my way!$"

Route13_Text_PerryDefeat::
    .string "The wind turned!$"

Route13_Text_PerryPostBattle::
    .string "I'm beat.\n"
    .string "I guess I'll FLY home.$"

Route13_Text_LolaIntro::
    .string "Sure, I'll play with you, sweetie.$"

Route13_Text_LolaDefeat::
    .string "Oh!\n"
    .string "You little beast!$"

Route13_Text_LolaPostBattle::
    .string "I wonder which is stronger, male or\n"
    .string "female POKéMON?$"

Route13_Text_SheilaIntro::
    .string "Do you want to battle some\n"
    .string "POKéMON with me?$"

Route13_Text_SheilaDefeat::
    .string "It's over already?$"

Route13_Text_SheilaPostBattle::
    .string "I don't know anything about\n"
    .string "POKéMON actually.\p"
    .string "The ones I use… I picked them\n"
    .string "for their looks!$"

Route13_Text_JaredIntro::
    .string "What're you lookin' at?$"

Route13_Text_JaredDefeat::
    .string "Dang!\n"
    .string "Stripped gears!$"

Route13_Text_JaredPostBattle::
    .string "Get lost!$"

Route13_Text_RobertIntro::
    .string "I always go with bird POKéMON.\n"
    .string "I've dedicated myself to them.$"

Route13_Text_RobertDefeat::
    .string "Out of power!$"

Route13_Text_RobertPostBattle::
    .string "I wish I could fly like PIDGEY and\n"
    .string "PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
    .string "TRAINER TIPS\p"
    .string "Look, look!\n"
    .string "Look to the left of that post!$"

Route13_Text_SelectToSwitchItems::
    .string "TRAINER TIPS\p"
    .string "Use SELECT to switch items in the\n"
    .string "ITEMS window.$"

Route13_Text_RouteSign::
    .string "ROUTE 13\n"
    .string "North to SILENCE BRIDGE$"

Route13_Text_MayIHelpYou::
    .string "Birds sing to the tune\n"
    .string "of Flutes.\p"
    .string "Some of which can heal them.\p"
    .string "Want to buy some flutes?$"



Route13_Text_PleaseComeAgain::
    .string "Feel Free to come back\n"
    .string "If you want$"

Route13_Text_Whitney::
    .string "This place is full of Cute,\n"
    .string "Pokemon!\p"
    .string "I'm visiting KANTO in search\n"  
    .string "of more cute POKEMON as,\n"  
    .string "I want to become a GYM\n"  
    .string "LEADER one day!\p"  
    .string "And I think that opportunity\n"  
    .string "is gonna open up sooner\l"  
    .string "than ever!\p"  
    .string "I think it would be good\n"  
    .string "if we battled\p"   
    .string "Although I'm warning you,\n"  
    .string "I'm good!$"  


Route13_Text_WhitneyDefeat::
    .string "Sob... ...Waaaaaaah!\p"  
    .string "You're mean!\n"  
    .string "You shouldn't be so\n"  
    .string "serious!\p"  
    .string "You...you child, you!\n"  
    .string "Waaaaah! Waaaaah!\p"  
    .string "...Snivel, hic...\n"  
    .string "...You meanie!$"  

Route13_Text_WhitneyPostBattle::
    .string "Ah, that was a good cry!\p"
    .string "I mean, you're the CHAMPION\n"    
    .string "After all, You're Very Strong!\p"    
    .string "Come for a visit again!\p"  
    .string "Bye-bye!$"  

Route13_Text_NoWhitney::
    .string "Can't Stand this\n"
    .string "Cute Face?$"

Route13_Text_YesWhitney::
    .string "Prepare to lose\n"
    .string "To my Cute Face!$"

Route13_Text_RematchWhitney::
    .string "Oh you're back!\p"
    .string "You could go with another\n"
    .string "battle with this Cutie!$"

Route13_Text_RematchWhitneyDefeat::
    .string "You really are strong!\p"  
    .string "But I won't lose next time!$"  

Route13_Text_YesRematchWhitney::
    .string "Prepare to lose\n"
    .string "To my Cute Face!$"

Route13_Text_RematchWhitneyPostBattle::
    .string "Don't look at me!\p"
    .string "I'm not Crying this Time!$"

