ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This POKéMON GYM is always closed.\p"
    .string "I wonder who the LEADER is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "I go shopping in PEWTER CITY\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "VIRIDIAN FOREST when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "Do you know how to catch pokemon?$"

ViridianCity_Text_DontKnow::
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_DoKnow::
    .string "Seems like you do know how to\n"
    .string "catch a POKéMON?\p"
    .string "But I think you should still have this!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

ViridianCity_Text_Pokedude::
    .string "Yo What's Up Champion!\p"
    .string "I'm just visiting my hometown\n"
    .string "after what happened earlier.\p"
    .string "Very Unfortunate that it happened.\p"
    .string "But that's in the past!\p"
    .string "We will found a new leader someday!\p"
    .string "I also heard you talked with my\n"
    .string "Grandpa also, he really helped you\l"
    .string "into the Champion you are Today!\p"
    .string "Anyways since we are here,\n"
    .string "I was wondering if we could\l"
    .string "have a battle$"

ViridianCity_Text_PokedudeDefeat::
    .string "Wow, you really are the Champion!$"

ViridianCity_Text_PokedudePostBattle::
    .string "That some good Champion Level\n"
    .string "Strength I see!\p"
    .string "I also wonder if the TEACHY TV\n"
    .string "helped you in this Journey!\p"
    .string "I would also like to give you this.\p"
    .string "It helped strengthen my pokemon to\n"
    .string "NEW LEVELS!$"

ViridianCity_Text_PokedudePostGift::
    .string "Continue to Grow Further!$"

ViridianCity_Text_NoPokedude::
    .string "Maybe some other time.$"

ViridianCity_Text_YesPokedude::
    .string "Ok, my Pokemon are Ready!\p"
    .string "Get ready Champion!\p"
    .string "Let's Battle!$"

ViridianCity_Text_RematchPokedude::
    .string "Want to rematch?$"

ViridianCity_Text_RematchPokedudeDefeat::
    .string "Wow, you really are the Champion!$"

ViridianCity_Text_PostRematchPokedude::
    .string "That some good Champion Level\n"
    .string "Strength I see!\p"
    .string "I also wonder if the TEACHY TV\n"
    .string "helped you in this Journey!\p"
    .string "Continue to Grow Further!$"

