PokemonLeague_AgathasRoom_Text_Intro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "I hear OAK's taken a lot of\n"
    .string "interest in you, child.\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "Back again, eh?\p"  
    .string "Seen PROF. OAK lately?\n"  
    .string "Still fond of you, I bet!\p"  
    .string "He's softened, unlike me.\p"  
    .string "I relish the thrill of battle!\p"  
    .string "Let's see if you've grown!\n"  
    .string "Are you ready, {PLAYER}?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"  

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "You win!\p"
    .string "I see what the old duff sees in\n"
    .string "you now.\p"
    .string "I have nothing else to say.\n"
    .string "Run along now, child!$"

PokemonLeague_AgathasRoom_Text_Defeat2::
    .string "Oh, my!\p"  
    .string "You've grown even stronger!$"  

PokemonLeague_AgathasRoom_Text_PostBattle2::
    .string "Well earned, CHAMPION!\n"  
    .string "You've grown mighty!\p"  
    .string "You've earned OAK's respect\n"  
    .string "as well as mine.\p"  
    .string "Now, go!\p"  
    .string "Show the others what you're\n"  
    .string "made of, {PLAYER}!$" 
