# 1 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"

# 2 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
Route2_ViridianForest_SouthEntrance_MapScripts::
# 3 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"

# 5 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
# 6 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
# 7 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	end
# 8 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"

# 9 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
# 10 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
# 11 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	end
# 12 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"

# 13 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
Route2_ViridianForest_SouthEntrance_EventScript_Pichu::
# 14 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
# 15 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	goto MysteryEventScript_SurfPichu
# 16 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	end
