ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Whimper… Sniff…\n"
    .string "Oh! Please, help!\p"
    .string "A scary POKéMON appeared there\n"
    .string "a little while ago.\p"
    .string "It kept scaring.\n"
    .string "It made LOSTELLE scared.\p"
    .string "I'm too scared to move!\n"
    .string "But I want to go home…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Oh! Here it comes again!\n"
    .string "No! Go away! It's scaring me!\p"
    .string "Waaaaaaah!\n"
    .string "I want my daddy!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Ohh! That was so scary!\n"
    .string "Thank you!\p"
    .string "LOSTELLE came to pick some\n"
    .string "BERRIES.\p"
    .string "You can have this!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "What's your name?\p"
    .string "LOSTELLE's scared, so can I go\n"
    .string "with you to my daddy's house?\p"
    .string "Okay!\n"
    .string "Let's go home!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Your BERRY POUCH is full.\n"
    .string "I guess you don't want this.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Welcome to the BERRY FOREST\p"
    .string "Be friendly and share BERRIES with\n"
    .string "others and POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Beware of wild, BERRY-loving\n"
    .string "POKéMON!$"

ThreeIsland_BerryForest_Text_CruelKing::  
    .string "I am the CRUEL KING!\p"  
    .string "An Apex Trainer that uses\n"  
    .string "fast and strong POKEMON!\p"  
    .string "Are you ready for my skill?$"  

ThreeIsland_BerryForest_Text_CruelKingDefeat::  
    .string "I think you're the APEX\n"  
    .string "Trainer here!$"  

ThreeIsland_BerryForest_Text_CruelKingPostBattle::  
    .string "Huh. Great Apex skill\n"  
    .string "you exerted, CHAMPION.\p"  
    .string "Continue to be the Apex Trainer!$"  

ThreeIsland_BerryForest_Text_NoCruelKing::  
    .string "Seems like you are\n"  
    .string "scared.$"  

ThreeIsland_BerryForest_Text_YesCruelKing::  
    .string "You don't know how\n"  
    .string "cruel I am.$"  

ThreeIsland_BerryForest_Text_RematchCruelKing::  
    .string "Back for more cruelty?$"  

ThreeIsland_BerryForest_Text_RematchCruelKingDefeat::  
    .string "Seems Champion-level to me!$"  

ThreeIsland_BerryForest_Text_YesRematchCruelKing::  
    .string "You will lose this!\p"  
    .string "I will win!$"  

ThreeIsland_BerryForest_Text_RematchCruelKingPostBattle::  
    .string "Huh. Great Apex skill\n"  
    .string "you exerted, CHAMPION.\p"  
    .string "Continue to be an Apex Trainer!$"  


Text_6Leaders::
    .string "There are 7 masters of\n"  
    .string "the SEVII ISLANDS.\p"  
    .string "Defeat the 6 of us to be\n"  
    .string "able to fight the\l"  
    .string "SUPREME LEADER on\l"  
    .string "SEVEN ISLAND.$"  

