DiglettsCave_B1F_Text_Freddy::
    .string "Har Har Har Har Har.$"

DiglettsCave_B1F_Text_FreddyDefeat::
    .string "Har Har Har Har Har!$"

DiglettsCave_B1F_Text_FreddyPostBattle::
    .string "Har Har Har Har Har!$"

DiglettsCave_B1F_Text_NoFreddy::
    .string "Har Har Har Har Har!$"

DiglettsCave_B1F_Text_YesFreddy::
    .string "Har Har Har Har Har!$"

DiglettsCave_B1F_Text_RematchFreddy::
    .string "Har Har Har Har Har?$"


DiglettsCave_B1F_Text_RematchFreddyDefeat::
    .string "Har!$"

DiglettsCave_B1F_Text_PostRematchFreddy::
    .string "Har Har Har.$"
